/* ==========================================================================
   MERAK ÇARKI — İÇERİK HAVUZU            merak/merakveri.js
   --------------------------------------------------------------------------
   Ders başında sınıfın dikkatini toplamak için dört tür kart. Her türde
   36 kart var: 36 haftalık öğretim yılında bir sınıf HER HAFTA aynı türü
   çekse bile kart tekrar etmez (tekrar etmeme kaydı merakcarki.js'te).

   KART BİÇİMİ
     id     benzersiz — TEKRAR KAYDI BUNA GÖRE tutulur, asla değiştirme.
            Değiştirirsen o kart bütün sınıflarda "hiç çıkmamış" sayılır.
     bas    başlık (kartın üstünde, büyük)
     ic     gövde — sınıfa okunan kısım
     cevap  gizli kısım: fıkranın sonu, bulmacanın cevabı, kelimenin kökü.
            "Cevabı Aç" düğmesine basılınca görünür. Boşsa düğme çıkmaz.
     ar     (isteğe bağlı) Arapça karşılık/ek — Arapça yazı tipiyle çizilir

   YENİ KART EKLEME: ilgili dizinin SONUNA ekle, id'yi sıradaki numaradan
   ver (f37, k37…). Sıra önemli değil, çark rastgele seçiyor.

   FIKRALAR: Nasreddin Hoca ve Arap dünyasındaki karşılığı Cuhâ (جُحا)
   etrafında anlatılagelen halk fıkraları; buradaki metinler kısa birer
   özettir.
   ========================================================================== */
window.MERAK_VERI = {

/* ══════════════════════════════════════════════════ 1) FIKRA (36) */
fikra: [
{ id:'f01', bas:'Kazan Doğurdu', ar:'جُحا',
  ic:'Hoca komşusundan kazan ödünç alır. Geri verirken içine küçük bir tencere koyar: «Kazanın doğurdu.» Komşu sevinerek alır. Bir süre sonra Hoca kazanı yine ister, ama bu kez geri getirmez. Komşu sorunca…',
  cevap:'«Kazan öldü» der. Komşu, «Hiç kazan ölür mü?» diye itiraz edince Hoca cevabı yapıştırır: «Doğurduğuna inandın da öldüğüne mi inanmıyorsun?»' },
{ id:'f02', bas:'Ye Kürküm Ye',
  ic:'Hoca eski kıyafetiyle davete gider, kimse yüzüne bakmaz. Eve dönüp güzel kürkünü giyer, yeniden gelir; bu kez el üstünde tutulur, sofranın başına buyur edilir. Hoca yemeği kürkünün yenine dökmeye başlar.',
  cevap:'«Ye kürküm ye!» der. «Anlaşılan bu ikram bana değil, sanaymış.»' },
{ id:'f03', bas:'Parayı Veren Düdüğü Çalar',
  ic:'Hoca şehre giderken çocuklar ondan bir şeyler ister; biri düdük ister ama parasını verir. Hoca dönüşte yalnız ona düdük getirir. Ötekiler «Bize niye yok?» diye sorunca…',
  cevap:'«Parayı veren düdüğü çalar» der.' },
{ id:'f04', bas:'Göle Maya Çalmak',
  ic:'Hoca göl kıyısında bir kâse yoğurdu suya karıştırıyor. Geçenler sorar: «Hocam ne yapıyorsun?» «Göle maya çalıyorum.» «Hiç göl maya tutar mı?»',
  cevap:'Hoca gülümser: «Ya tutarsa?»' },
{ id:'f05', bas:'Bindiği Dalı Kesmek',
  ic:'Hoca ağaca çıkmış, oturduğu dalı kesiyor. Yoldan geçen biri seslenir: «Hocam düşeceksin!» Hoca aldırmaz, adam yoluna gider. Az sonra dal kırılır, Hoca yere düşer. Peşinden koşup adamı yakalar:',
  cevap:'«Sen düşeceğimi bildin, madem gaipten haber veriyorsun, söyle bakalım ben ne zaman öleceğim?»' },
{ id:'f06', bas:'İpe Un Sermek',
  ic:'Komşu, Hoca\'dan ip ister. Hoca içeri girip çıkar: «Olmaz, ipe un serdik.» Komşu şaşırır: «Hiç ipe un serilir mi?»',
  cevap:'«Vermeye gönlün olmayınca serilir» der Hoca.' },
{ id:'f07', bas:'Sen de Haklısın',
  ic:'Hoca kadı vekiliyken davacıyı dinler: «Haklısın.» Davalıyı dinler: «Sen de haklısın.» Yanındaki çıkışır: «Hocam, ikisi birden nasıl haklı olur?»',
  cevap:'Hoca ona döner: «Vallahi sen de haklısın.»' },
{ id:'f08', bas:'Kuyudaki Ay',
  ic:'Hoca gece kuyuya bakar, suda ayı görür: «Ay kuyuya düşmüş!» Hemen ipi, çengeli getirip çekmeye başlar. Çengel bir taşa takılır, Hoca var gücüyle asılınca ip kopar, kendisi sırtüstü yere serilir. Gökyüzünde ayı görünce…',
  cevap:'«Çok zahmet oldu ama olsun» der, «hiç değilse ay yerine kondu.»' },
{ id:'f09', bas:'Kavuk ve Mektup',
  ic:'Okuma bilmeyen bir adam Hoca\'ya mektup getirir. Hoca bakar, yazı okunmuyor: «Ben bunu okuyamam.» Adam kızar: «Kavuk taşımaya utanmıyor musun?»',
  cevap:'Hoca kavuğunu çıkarıp adamın başına koyar: «Madem iş kavuktaysa, buyur sen oku.»' },
{ id:'f10', bas:'Fincancı Katırları',
  ic:'Hoca eşeğiyle dar bir yolda giderken önüne yüklü katırlar çıkar. Yol vermek zorunda kalır, üstelik bir de itilip kakılır. Kızıp bağırmak ister ama vazgeçer.',
  cevap:'«Fincancı katırlarını ürkütmeye gelmez» der — yani gücü yetmeyeceğin işe girişme.' },
{ id:'f11', bas:'Buyurun Cenaze Namazına',
  ic:'Hoca\'ya sorarlar: «Cenazede tabutun neresinde yürümek gerekir, önünde mi arkasında mı, sağında mı solunda mı?»',
  cevap:'«İçinde olmayın da neresinde olursanız olun» der.' },
{ id:'f12', bas:'Damdan Düşen',
  ic:'Hoca damdan düşer, canı yanar. Komşular başına toplanıp teselli eder, ama hiçbiri derdini anlamaz. Hoca kalabalığa sorar: «İçinizde hiç damdan düşen var mı?»',
  cevap:'Kimse çıkmayınca: «Öyleyse anlatmanın faydası yok» der. Bir derdi ancak onu yaşayan bilir.' },
{ id:'f13', bas:'Yorgan Gitti Kavga Bitti',
  ic:'Gece sokakta gürültü olur. Hoca yorganı sırtına alıp bakmaya çıkar. Kavga edenler yorganı kapıp kaçar. İçeri dönünce hanımı sorar: «Kavga neymiş?»',
  cevap:'«Yorgan gitti, kavga bitti» der Hoca.' },
{ id:'f14', bas:'Kazandaki Kaşık',
  ic:'Hoca çok büyük bir kazanda pişen aşa uzun bir kaşık daldırır, tadına bakar, ağzı yanar. Yanındaki «Neden kaşığı bu kadar uzattın?» diye sorar.',
  cevap:'«Yakın olmasaydım ağzım yanmazdı» der. Bazı sıcaklıklara mesafe gerekir.' },
{ id:'f15', bas:'Eşeğe Ters Binmek',
  ic:'Hoca öğrencilerinin önünde eşeğe ters biner. Öğrenciler güler: «Hocam ters bindin!» ',
  cevap:'«Hayır» der Hoca, «ben doğru bindim, eşek ters duruyor. Ben önden gitsem size sırtımı dönmüş olurdum; siz önden gitseniz bu kez ben sizi göremezdim.»' },
{ id:'f16', bas:'Hırsızın Hiç mi Suçu Yok',
  ic:'Hoca\'nın evine hırsız girer, ne var ne yok götürür. Hanımı «Senin yüzünden oldu, kapıyı sağlam kapatmadın» diye söylenir. Komşular da bir bir suçu Hoca\'ya yükler.',
  cevap:'Hoca sorar: «Peki, hırsızın hiç mi suçu yok?»' },
{ id:'f17', bas:'Kırk Yıllık Sirke',
  ic:'Komşu, Hoca\'dan kırk yıllık sirkesinden ister. Hoca vermez. Komşu üsteler: «Hocam, o kadar çok ki, azını versen ne olur?»',
  cevap:'«Herkese verseydim kırk yıl durur muydu?» der.' },
{ id:'f18', bas:'Testi Kırılmadan',
  ic:'Hoca çocuğa testiyi verip çeşmeye yollar, sonra da bir tokat atar: «Sakın kırma!» Görenler şaşırır: «Daha kırmadan niye dövdün?»',
  cevap:'«Kırdıktan sonra dövmenin ne faydası var?» der Hoca.' },
{ id:'f19', bas:'Acele Etme',
  ic:'Hoca\'ya «Kıyamet ne zaman kopacak?» diye sorarlar. Hoca düşünür: «Hangisi? Küçüğü mü büyüğü mü?» «İkisi de var mı?»',
  cevap:'«Hanımım ölürse küçüğü, ben ölürsem büyüğü kopar» der.' },
{ id:'f20', bas:'Eşek Okur mu?',
  ic:'Timur, Hoca\'ya «Şu eşeğe okuma öğretebilir misin?» diye sorar. Hoca «Öğretirim ama zaman ve para ister» der. On iki yıl süre ister. Dostları telaşlanır: «Bu işin sonu kötü!»',
  cevap:'Hoca sakindir: «On iki yılda ya padişah ölür, ya eşek, ya da ben.»' },
{ id:'f21', bas:'Ödünç Kazanın Faydası',
  ic:'Hoca, komşusunun kapısını çalar: «Eşeğini ödünç verir misin?» Komşu «Eşek evde yok» der. Tam o sırada ahırdan eşeğin sesi gelir. Hoca «Hani yoktu?» diye çıkışır.',
  cevap:'Komşu kızar: «Ayıp sana! Benim sözüme mi inanırsın, eşeğin sözüne mi?»' },
{ id:'f22', bas:'Doğru Söyleyeni',
  ic:'Hoca\'ya sorarlar: «Neden hep doğruyu söylüyorsun, başına iş açıyorsun?» Hoca güler.',
  cevap:'«Doğru söyleyeni dokuz köyden kovarlar» der, «ama yalan söyleyeni bir köy bile istemez.»' },
{ id:'f23', bas:'Kaybolan Yüzük',
  ic:'Cuhâ, evinin önünde bir şey arıyordur. Komşusu «Ne arıyorsun?» diye sorar. «Yüzüğümü, evin içinde düşürdüm.» Komşu şaşırır: «Peki neden dışarıda arıyorsun?»',
  cevap:'«Çünkü burası aydınlık» der. Kolayımıza geleni aramak, aradığımızı bulmaya yetmez.' },
{ id:'f24', bas:'Cuhâ ve Çivi', ar:'مِسْمار جُحا',
  ic:'Cuhâ evini satar ama duvardaki bir çiviyi kendine ayırtır. Sonra her fırsatta gelip «çivime bakacağım» diye eve girer, oturur, kalkmaz. Sonunda yeni sahibi dayanamaz, evi bırakıp gider.',
  cevap:'Arapçada bugün hâlâ bahane arayan kişi için «Cuhâ\'nın çivisi» denir: küçük bir bahane, koca bir işgale dönüşür.' },
{ id:'f25', bas:'Eşeğin Yükü',
  ic:'Cuhâ eşeğine biner, oğlu yanında yürür; görenler «Zavallı çocuk» der. Oğlunu bindirir, kendi yürür; «Şu saygısız çocuğa bak» derler. İkisi birden biner; «Hayvana yazık» derler. İkisi de iner; «Eşek dururken yürüyene bak» derler.',
  cevap:'Cuhâ oğluna döner: «Gördün mü? Herkesi memnun etmeye çalışan, kendini yorar da yine de birini kızdırır.»' },
{ id:'f26', bas:'Kokunun Parası',
  ic:'Yoksul bir adam, aşçının önünde ekmeğini kebabın kokusuna tutup yer. Aşçı parasını ister, iş kadıya düşer. Kadı olarak Cuhâ, adamın kesesini alıp şıngırdatır ve aşçıya uzatmadan geri verir.',
  cevap:'«Kokunun karşılığı, paranın sesidir» der.' },
{ id:'f27', bas:'Uzun Yol',
  ic:'Yolcu, Cuhâ\'ya sorar: «Şehre ne kadar sürer?» Cuhâ cevap vermez. Adam söylenerek yürümeye başlar. Birkaç adım sonra Cuhâ arkasından seslenir: «İki saat sürer!» Adam kızar: «Niye önce söylemedin?»',
  cevap:'«Ne hızda yürüdüğünü görmeden nasıl söyleyeyim?» der.' },
{ id:'f28', bas:'Üç Kuruşluk Akıl',
  ic:'Hoca pazarda çok ucuza bir kuş satın alır, eve getirir. Hanımı bakar: «Bu bildiğimiz karga!» Hoca savunur: «Satıcı bunun konuşacağını söyledi.»',
  cevap:'Hanımı güler: «Konuşmasına konuşur da, seni kandırmayı nereden öğrenmiş?»' },
{ id:'f29', bas:'Merdivenin Parası',
  ic:'Hoca komşudan merdiven ister, komşu vermez. Ertesi gün komşu merdiven ister; Hoca verir ama bir şart koşar: «Merdiven bizim dama kadar gelir, ötesine gitmez.»',
  cevap:'Komşu «Öyle merdiven mi olur?» deyince Hoca cevabı verir: «Vermek istemeyince her merdiven kısalır.»' },
{ id:'f30', bas:'Şu Da Gitsin',
  ic:'Hoca kışın soğukta ateşi yakmak için odun kırıyor. Her odunu ateşe atarken bir şey mırıldanıyor. Merak edip sorarlar.',
  cevap:'«Sabırsızlığımı sayıyorum» der. «Her sıkıntıya bir odun; ateş ısıtınca ikisi de biter.»' },
{ id:'f31', bas:'Güneş mi Ay mı?',
  ic:'Hoca\'ya sorarlar: «Sence hangisi daha faydalı, güneş mi ay mı?» Hoca hiç düşünmeden cevap verir.',
  cevap:'«Elbette ay» der. «Çünkü ay, karanlıkta doğar; güneş zaten aydınlıkta.»' },
{ id:'f32', bas:'Hesabı Kim Öder',
  ic:'Hoca ile arkadaşı lokantaya gider. Hesap gelince ikisi de cüzdanını arar gibi yapar. Hoca uzun uzun ceplerini karıştırır, sonunda doğrulur.',
  cevap:'«Bulamadım» der, «ama merak etme, arayışım samimiydi.»' },
{ id:'f33', bas:'Hocanın Terazisi',
  ic:'Hoca\'dan bir şeyin ağırlığını tahmin etmesini isterler. Hoca eline alır, tartar gibi yapar, gözlerini kapatır, sonra kesin bir rakam söyler. Tartarlar; tutmaz.',
  cevap:'«Tahminim doğruydu» der, «yanlış olan teraziniz.» — İnsan yanıldığını kabul etmeyince suç hep başkasında kalır.' },
{ id:'f34', bas:'Sessizliğin Bedeli',
  ic:'Bir meclis kurulur, herkes bilgisini gösterir. Hoca hiç konuşmaz. Sonunda birisi sorar: «Hocam, sen niye susuyorsun?»',
  cevap:'«Susarak kaybettiğim hiçbir söz yok» der, «ama konuşarak kaybettiğim çok arkadaş var.»' },
{ id:'f35', bas:'Kayıp Eşek',
  ic:'Hoca\'nın eşeği kaybolur. Aramaya çıkar, bir yandan da şükrederek yürür. Görenler şaşırır: «Eşeğin kayıp, sen şükrediyorsun!»',
  cevap:'«Üstünde olsaydım» der, «şimdi ben de kayıp olurdum.»' },
{ id:'f36', bas:'İki Kere İki',
  ic:'Hoca\'ya «İki kere iki kaç eder?» diye sorarlar. Hoca «Dört» der. Adam itiraz eder: «Bana kalırsa beş.» Hoca ısrar etmez, tartışmaz.',
  cevap:'«Peki» der, «sen beş elmanın parasını öde, ben dördünü vereyim.» Bazı tartışmalar sözle değil, sonuçla biter.' }
],

/* ══════════════════════════════════════════════════ 2) KELİME KÖKENİ (36) */
koken: [
{ id:'k01', bas:'Kitap · Mektep · Kâtip', ar:'ك ت ب',
  ic:'Bu üç kelimenin de aynı kökten geldiğini biliyor muydunuz? Peki ortak kökleri ne ve ne anlama geliyor?',
  cevap:'Kök: ك ت ب (ketebe) = YAZMAK. kitâb = yazılan şey · mektep = yazı yazılan yer · kâtip = yazan kişi · mektup = yazılıp gönderilen. Yani okul, aslında "yazı evi".' },
{ id:'k02', bas:'Ders · Medrese · Müderris', ar:'د ر س',
  ic:'"Ders" kelimesi Arapçadan. Aynı kökten iki kelime daha var ve ikisi de okulla ilgili. Tahmin edin.',
  cevap:'Kök: د ر س (derese) = DERS ÇALIŞMAK, okumak. medrese = ders çalışılan yer · müderris = ders veren · tedris = öğretim.' },
{ id:'k03', bas:'İlim · Âlim · Muallim', ar:'ع ل م',
  ic:'Öğretmenin Arapçası "muallim". Bu kelime hangi kökten geliyor ve akrabaları kimler?',
  cevap:'Kök: ع ل م (alime) = BİLMEK. ilim = bilgi · âlim = bilen · muallim = bildiren, öğreten · talim = öğretme · malumat = bilinenler.' },
{ id:'k04', bas:'Minare Neden Böyle Adlandı?', ar:'ن و ر',
  ic:'Minare kelimesi camiyle değil, bambaşka bir şeyle ilgili. Neyle?',
  cevap:'Kök: ن و ر (nûr) = IŞIK. menâre = ışık konulan yer. Eskiden minarelerin tepesinde kandil yakılırdı; "nur" ile "minare" ve "münevver" (aydın) aynı ailedendir.' },
{ id:'k05', bas:'Cami · Cuma · Cemaat', ar:'ج م ع',
  ic:'Üçü de aynı kökten. Ortak anlam ne olabilir?',
  cevap:'Kök: ج م ع (cemea) = TOPLAMAK. câmi = toplayan (yer) · cum\'a = toplanma günü · cemaat = toplanmış topluluk · mecmua = toplanmış yazılar.' },
{ id:'k06', bas:'Hastane Neden "Hasta"+"hane"?', ar:'د ر س',
  ic:'"-hane" ekli kelimeler: hastane, kütüphane, postane, dershane. Bu ek hangi dilden ve ne demek?',
  cevap:'"-hâne" FARSÇADIR, "ev" demektir. Yani Türkçede Arapça kök + Farsça ek çok yaygındır: kütüb (kitaplar) + hâne = kitapların evi.' },
{ id:'k07', bas:'Hareket · Hareketli · Muharrik', ar:'ح ر ك',
  ic:'"Hareke" ile "hareket" arasında bir bağ var mı?',
  cevap:'Var! Kök: ح ر ك (harake) = HAREKET ETMEK. Harekeler harfi "hareketlendiren", ona ses veren işaretlerdir. Harekesiz harf duruyor (sâkin), harekeli harf hareket ediyor.' },
{ id:'k08', bas:'Sâkin Neden Hem Sessiz Hem Oturan?', ar:'س ك ن',
  ic:'"Sakin bir insan", "sakin mahalle", bir de gramerdeki "sâkin harf". Ortak kök ne?',
  cevap:'Kök: س ك ن (sekene) = DURMAK, yerleşmek. mesken = oturulan yer · iskân = yerleştirme · sükûn = durgunluk. Sâkin harf, hareketi olmayan yani "duran" harftir.' },
{ id:'k09', bas:'Kalp mi Kalıp mı?', ar:'ق ل ب',
  ic:'"Kalp", "inkılap" ve "kalıp" — üçü de mi akraba?',
  cevap:'Evet. Kök: ق ل ب (kalebe) = ÇEVİRMEK, döndürmek. kalb = sürekli dönen/değişen · inkılâb = alt üst olma, devrim · kālab = bir şeyi çevirip şekil veren şey, kalıp.' },
{ id:'k10', bas:'Misafir Neden Yolcudur?', ar:'س ف ر',
  ic:'"Misafir" ve "sefer" kelimeleri arasındaki bağ ne?',
  cevap:'Kök: س ف ر (sefere) = YOLCULUK ETMEK. sefer = yolculuk · müsâfir = yolculuk eden · sefâret = elçilik, sefir = elçi (yolculuğa gönderilen).' },
{ id:'k11', bas:'Hesap · Muhasebe · İhtisap', ar:'ح س ب',
  ic:'Matematikteki "hesap" kelimesinin Arapça kökü ne?',
  cevap:'Kök: ح س ب (hasebe) = SAYMAK. hisâb = sayma, hesap · muhâsebe = karşılıklı hesaplaşma · hasbî = hesapsız, karşılıksız.' },
{ id:'k12', bas:'Nazar · Manzara · Nazariye', ar:'ن ظ ر',
  ic:'"Nazar değdi" ile "manzara" aynı kökten olabilir mi?',
  cevap:'Evet. Kök: ن ظ ر (nazara) = BAKMAK. nazar = bakış · manzara = bakılan yer · nazariye = teori, bakış açısı · münâzara = karşılıklı bakışma, tartışma.' },
{ id:'k13', bas:'Fikir · Tefekkür · Mütefekkir', ar:'ف ك ر',
  ic:'Aynı kökten, gittikçe derinleşen üç kelime. Fark ne?',
  cevap:'Kök: ف ك ر (fekera) = DÜŞÜNMEK. fikir = düşünce · tefekkür = derin derin düşünme · mütefekkir = düşünür. Aynı kökün kalıbı değişince anlamın "dozu" değişiyor.' },
{ id:'k14', bas:'Kelime Ailesi: Hüküm', ar:'ح ك م',
  ic:'hüküm, hâkim, hikmet, mahkeme, hükümet — beşi de aynı kökten. Ortak anlam ne?',
  cevap:'Kök: ح ك م (hakeme) = KARAR VERMEK, hükmetmek. hâkim = karar veren · mahkeme = karar verilen yer · hikmet = doğru kararın bilgisi · hükûmet = yönetim.' },
{ id:'k15', bas:'Selam ve İslam', ar:'س ل م',
  ic:'"Selam", "İslam", "teslim", "salim" — bu kelimeler arasında nasıl bir bağ var?',
  cevap:'Kök: س ل م (selime) = SAĞ SALİM OLMAK, esenlik. selâm = esenlik dileği · teslim = sağ salim ulaştırmak · sâlim = zarar görmemiş · selâmet = esenlik.' },
{ id:'k16', bas:'Talebe Ne İster?', ar:'ط ل ب',
  ic:'Öğrenciye neden "talebe" denir?',
  cevap:'Kök: ط ل ب (talebe) = İSTEMEK, aramak. Talebe = "isteyen, arayan" demek. talep = istek · matlûb = istenen · tâlib = isteyen. Öğrenci, bilgiyi isteyendir.' },
{ id:'k17', bas:'Hafız Ne Demek?', ar:'ح ف ظ',
  ic:'"Hafız", "muhafaza", "muhafız" — hangi kökten?',
  cevap:'Kök: ح ف ظ (hafiza) = KORUMAK, ezberlemek. hâfız = koruyan, ezberinde tutan · muhâfaza = koruma · mahfaza = koruyan kap. Hafıza kelimesi de buradan.' },
{ id:'k18', bas:'Fetih ve Anahtar', ar:'ف ت ح',
  ic:'"Fetih" ile "miftah" (anahtar) neden aynı kökten?',
  cevap:'Kök: ف ت ح (fetaha) = AÇMAK. fetih = açma · fâtih = açan · miftâh = açma aleti, anahtar. Fetih, kapalı bir yeri açmaktır.' },
{ id:'k19', bas:'Şehir mi Şahit mi?', ar:'ش ه د',
  ic:'"Şahit", "şehit", "şahadet" aynı kökten. Peki bağ ne?',
  cevap:'Kök: ش ه د (şehide) = GÖRMEK, tanık olmak. şâhid = tanık · şehâdet = tanıklık · şehîd = tanıklık eden. (Not: "şehir" bu kökten DEĞİL, Farsça "şehr"den gelir.)' },
{ id:'k20', bas:'Sanat ve Sanayi', ar:'ص ن ع',
  ic:'Sanat, sanayi, sun\'î (yapay) — hepsi aynı kökten.',
  cevap:'Kök: ص ن ع (sanea) = YAPMAK, imal etmek. san\'at = yapma işi · sınâat/sanayi = yapım işleri · masnû = yapılmış · sun\'î = yapma, yapay.' },
{ id:'k21', bas:'Adalet ve Mutedil', ar:'ع د ل',
  ic:'"Adalet" ile "mutedil" (ılımlı) arasındaki bağ ne?',
  cevap:'Kök: ع د ل (adele) = DENK OLMAK, dengelemek. adâlet = dengeyi kurmak · âdil = dengeli davranan · i\'tidâl = ölçülülük · muâdil = denk. Adalet önce bir denge fikridir.' },
{ id:'k22', bas:'Kader ve Kudret', ar:'ق د ر',
  ic:'"Kader", "kudret", "miktar", "takdir" — ortak kök ne söylüyor?',
  cevap:'Kök: ق د ر (kadera) = ÖLÇMEK, güç yetirmek. kader = ölçülüp belirlenmiş olan · miktâr = ölçü · takdîr = değer biçme · kudret = güç yetirme.' },
{ id:'k23', bas:'Haber ve Muhabir', ar:'خ ب ر',
  ic:'"Haber" Arapça. Aynı kökten gazetecilikte kullandığımız kelime hangisi?',
  cevap:'Kök: خ ب ر (habera) = BİLDİRMEK. haber = bildirilen · muhâbir = haber getiren · muhâbere = haberleşme · ihbâr = bildirme.' },
{ id:'k24', bas:'Rakam ve Satır', ar:'ر ق م · س ط ر',
  ic:'"Rakam" ve "satır" da Arapçadan. Asıl anlamları ne?',
  cevap:'ر ق م (rakame) = işaretlemek, yazmak → rakam = yazılan işaret. س ط ر (satara) = çizgi çekmek → satır = çizgi, yazı sırası · mistar = cetvel.' },
{ id:'k25', bas:'Tarih Neden "Tarih"?', ar:'أ ر خ',
  ic:'"Tarih" kelimesi hangi anlamdan geliyor?',
  cevap:'Kök: أ ر خ (erraha) = TARİH DÜŞMEK, bir olaya zaman belirtmek. târîh önce "olayın zamanını yazmak", sonra "geçmişin bilgisi" anlamını kazanmıştır. müverrih = tarihçi.' },
{ id:'k26', bas:'Kelime Ailesi: Nakil', ar:'ن ق ل',
  ic:'nakil, nakliye, menkul, intikal — ortak anlam?',
  cevap:'Kök: ن ق ل (nakale) = TAŞIMAK. nakil = taşıma · nakliye = taşımacılık · menkûl = taşınabilir (taşınmaz = gayrimenkul) · intikâl = bir yerden bir yere geçme.' },
{ id:'k27', bas:'Sohbet ve Sahip', ar:'ص ح ب',
  ic:'"Sohbet" ile "sahip" arasında ne var?',
  cevap:'Kök: ص ح ب (sahibe) = ARKADAŞLIK ETMEK, birlikte olmak. sâhib = arkadaş, birlikte olan · sohbet = arkadaşlık, birlikte konuşma · ashâb = arkadaşlar.' },
{ id:'k28', bas:'Bereket ve Tebrik', ar:'ب ر ك',
  ic:'"Tebrik ederim" derken aslında ne diliyoruz?',
  cevap:'Kök: ب ر ك (bâreke) = BEREKETLİ KILMAK. bereket = artış, bolluk · mübârek = bereketli · tebrîk = "bereketli olsun" demek. Yani tebrik, bir bolluk duasıdır.' },
{ id:'k29', bas:'Hürmet ve Haram', ar:'ح ر م',
  ic:'"Haram", "harem", "hürmet", "ihram" aynı kökten. Nasıl?',
  cevap:'Kök: ح ر م (harume) = DOKUNULMAZ OLMAK. harâm = dokunulması yasak · harem = korunan, girilmeyen yer · hürmet = dokunulmazlık tanıma, saygı · ihrâm = bazı şeylerin kendine yasaklandığı hâl.' },
{ id:'k30', bas:'Sadaka ve Sadık', ar:'ص د ق',
  ic:'"Sadaka" ile "sadık" (dürüst) neden aynı kökten?',
  cevap:'Kök: ص د ق (sadaka) = DOĞRU OLMAK. sâdık = doğru sözlü · sadaka = verenin samimiyetini gösteren · tasdîk = doğrulama · sıdk = doğruluk.' },
{ id:'k31', bas:'Kelime Ailesi: Vakit', ar:'و ق ت',
  ic:'"Vakit", "muvakkat", "mîkat" — ortak anlam ne?',
  cevap:'Kök: و ق ت (vakkate) = ZAMAN BELİRLEMEK. vakit = belirlenmiş zaman · muvakkat = geçici, süreli · mîkât = belirli zaman/yer. Vakit, "sınırı olan zaman"dır.' },
{ id:'k32', bas:'Marifet ve Örf', ar:'ع ر ف',
  ic:'"Marifet", "arif", "tarif", "örf" — dördü de aynı kökten.',
  cevap:'Kök: ع ر ف (arafe) = TANIMAK, bilmek. ma\'rifet = tanıma, ustalık · ârif = tanıyan · ta\'rîf = tanıtma · örf = herkesin tanıdığı, bilinen âdet.' },
{ id:'k33', bas:'Kelime Ailesi: Kemal', ar:'ك م ل',
  ic:'"Mükemmel" kelimesinin kökü ne anlama geliyor?',
  cevap:'Kök: ك م ل (kemule) = TAMAMLANMAK. kemâl = olgunluk, tamlık · kâmil = tam, olgun · mükemmel = tamamlanmış · tekmîl = tamamlama.' },
{ id:'k34', bas:'Tabiat ve Matbaa', ar:'ط ب ع',
  ic:'"Tabiat" ile "matbaa" aynı kökten. Bağ ne?',
  cevap:'Kök: ط ب ع (tabea) = BASMAK, damga vurmak. tab\' = basma, mizaç (insana vurulmuş damga) · tabîat = yaratılıştan gelen · matbaa = basım yeri · intibâ = zihne basılan iz, izlenim.' },
{ id:'k35', bas:'İstiklâl Nereden Gelir?', ar:'ق ل ل',
  ic:'"İstiklâl" (bağımsızlık) hangi kökten ve nasıl bu anlamı kazanmış?',
  cevap:'Kök: ق ل ل (kalle) = AZ OLMAK. istiklâl kalıbı "kendini az/yalnız başına görmek" → başkasına muhtaç olmamak → bağımsızlık. kalîl = az · ekalliyet = azınlık.' },
{ id:'k36', bas:'Cihat ve İçtihat', ar:'ج ه د',
  ic:'"İçtihat" ile "cihat" aynı kökten. Ortak anlam ne?',
  cevap:'Kök: ج ه د (cehede) = ÇABA GÖSTERMEK, gayret etmek. cehd = çaba · cihâd = çaba harcamak · ictihâd = bütün gücünü kullanarak hüküm çıkarmaya çalışmak · mücâhid = çaba gösteren.' }
],

/* ══════════════════════════════════════════════════ 3) KÜLTÜR & BİLİM (36) */
kultur: [
{ id:'g01', bas:'Sıfır Nereden Geldi?',
  ic:'Bugün kullandığımız rakamlara "Arap rakamları" deniyor. Peki bu rakamlar aslında nerede doğdu?',
  cevap:'Hindistan\'da. Hint matematikçilerinin geliştirdiği ondalık sistem ve sıfır, Arap âlimleri aracılığıyla İslam dünyasına, oradan da Avrupa\'ya geçti. Avrupalılar bu yüzden "Arap rakamları" der; Araplar ise "Hint rakamları" (أرقام هندية) der.' },
{ id:'g02', bas:'Algoritma Kelimesi Kimden Kaldı?',
  ic:'Bilgisayarın temeli sayılan "algoritma" kelimesi bir kişinin adından geliyor. Kim?',
  cevap:'Hârizmî (el-Harezmî). 9. yüzyılda yaşayan bu matematikçinin adı Latinceye "Algoritmi" diye geçti. "Cebir" (algebra) kelimesi de onun kitabının adındaki "el-cebr"den gelir.' },
{ id:'g03', bas:'Kahve Nereden Çıktı?',
  ic:'Kahve hangi bölgede yetiştirilmeye ve içilmeye başladı?',
  cevap:'Etiyopya\'da keşfedildiği, Yemen\'de yaygınlaştığı kabul edilir. Arapça "kahve" (قهوة) kelimesi Türkçeye, oradan Avrupa dillerine "café/coffee" olarak geçti. Yemen\'in Mokka limanı yüzünden bir kahve türüne hâlâ "mocha" denir.' },
{ id:'g04', bas:'Dünyanın En Eski Üniversitesi',
  ic:'UNESCO ve Guinness\'e göre hâlâ faaliyette olan en eski üniversite hangisi, nerede?',
  cevap:'Fas\'ın Fez şehrindeki el-Karaviyyîn. 859 yılında Fâtıma el-Fihrî adında bir kadın tarafından kurulmuştur ve bugün hâlâ eğitim vermektedir.' },
{ id:'g05', bas:'Bir Işık Yılı Zaman mı?',
  ic:'"Işık yılı" bir süre ölçüsü müdür?',
  cevap:'Hayır, UZAKLIK ölçüsüdür: ışığın bir yılda aldığı yol, yaklaşık 9,46 trilyon kilometre. Adında "yıl" geçtiği için çok karıştırılır.' },
{ id:'g06', bas:'Bal Neden Bozulmaz?',
  ic:'Arkeologlar binlerce yıllık mezarlarda hâlâ yenebilir durumda bal buldu. Nasıl oluyor bu?',
  cevap:'Balda su oranı çok düşük, şeker oranı çok yüksektir; bu ortamda bakteriler yaşayamaz. Ayrıca doğal olarak asidiktir. Ağzı kapalı ve kuru tutulduğunda pratikte bozulmaz.' },
{ id:'g07', bas:'Develer Hörgüçte Su mu Taşır?',
  ic:'Çölün gemisi develerin hörgücünde ne var?',
  cevap:'Su değil, YAĞ. Hörgüç bir yağ deposudur; yiyecek bulunmadığında enerji sağlar. Develerin susuzluğa dayanması ise kanlarının ve böbreklerinin özel yapısından kaynaklanır.' },
{ id:'g08', bas:'Arapça Kaç Kişinin Ana Dili?',
  ic:'Arapça dünyada kaç ülkede resmî dil?',
  cevap:'Yirmiden fazla ülkede resmî dildir ve Birleşmiş Milletler\'in altı resmî dilinden biridir. Konuşulan lehçeler ülkeden ülkeye çok değişir; ortak yazı dili ise Fasih Arapçadır.' },
{ id:'g09', bas:'Sağdan Sola Yazan Diller',
  ic:'Arapçadan başka sağdan sola yazılan hangi diller var?',
  cevap:'İbranice, Farsça, Urduca, Peştuca, Kürtçenin Sorani lehçesi ve eski Süryanice. Rakamlar ise bu dillerin çoğunda soldan sağa yazılır — yani bir satırda iki yön birden bulunabilir.' },
{ id:'g10', bas:'Bir Günde Kaç Kez Nefes Alırız?',
  ic:'Dinlenme hâlindeki bir yetişkin günde yaklaşık kaç kez nefes alır?',
  cevap:'Dakikada ortalama 12-20 nefesten, günde kabaca 20.000 civarı. Kalp ise günde yaklaşık 100.000 kez atar.' },
{ id:'g11', bas:'Çöl Gerçekten Kumdan mı İbaret?',
  ic:'Sahra Çölü\'nün ne kadarı kum denizidir?',
  cevap:'Yaklaşık beşte biri. Geri kalanı taşlık plato, çakıl ovaları ve kayalıktır. "Çöl" tanımı kumla değil, yağış azlığıyla yapılır — bu yüzden Antarktika da bir çöldür.' },
{ id:'g12', bas:'Ayın Aynı Yüzü',
  ic:'Dünya\'dan Ay\'ın hep aynı yüzünü görürüz. Neden?',
  cevap:'Ay, kendi ekseni etrafında bir tam dönüşünü, Dünya etrafındaki bir turuyla aynı sürede tamamlar. Buna "gelgit kilitlenmesi" denir. Ay\'ın uzak yüzü ilk kez 1959\'da bir uzay aracıyla görüntülendi.' },
{ id:'g13', bas:'Kâğıt Nereden Yayıldı?',
  ic:'Kâğıt Çin\'de icat edildi. Peki İslam dünyasına ve oradan Avrupa\'ya nasıl geçti?',
  cevap:'8. yüzyılda Semerkant üzerinden yayıldı; Bağdat, Şam ve Kahire\'de kâğıt atölyeleri kuruldu. Avrupa kâğıtla, Endülüs ve Sicilya yoluyla tanıştı. Kâğıt ucuzlayınca kitap çoğalttı.' },
{ id:'g14', bas:'En Uzun Kelime Kaç Harf?',
  ic:'Türkçede uzun kelimeler yapım ve çekim ekleriyle üretilir. Peki Arapçada kelimeler nasıl uzar?',
  cevap:'Arapçada uzama çoğunlukla EKLE değil KALIPLA olur: aynı üç harfli kök, farklı kalıplara girerek onlarca kelime üretir. Türkçe "ekleyerek", Arapça "kalıba dökerek" büyür.' },
{ id:'g15', bas:'Gökyüzü Neden Mavi?',
  ic:'Havada mavi boya yok. Peki gökyüzü neden mavi görünür?',
  cevap:'Güneş ışığı atmosferdeki moleküllere çarpıp saçılır; kısa dalga boylu mavi ışık daha çok saçıldığı için gökyüzünü mavi görürüz. Gün batımında ışık daha kalın hava katmanından geçtiği için kırmızı-turuncu kalır.' },
{ id:'g16', bas:'Parmak İzi Neden Benzersiz?',
  ic:'İkizlerin bile parmak izi aynı değildir. Neden?',
  cevap:'Parmak izi sadece genlerle belirlenmez; anne karnındaki basınç, beslenme ve derinin büyüme hızı gibi rastlantısal etkenlerle şekillenir. Bu yüzden tek yumurta ikizlerinin bile izleri farklıdır.' },
{ id:'g17', bas:'Kum Saatinden Önce',
  ic:'Saat icat edilmeden önce Müslüman şehirlerde namaz vakitleri nasıl belirlenirdi?',
  cevap:'Gölge boyu ölçen güneş saatleriyle ve gökyüzü hesaplarıyla. Camilerde bu işle görevli "muvakkit" adında bir görevli bulunur, "muvakkithâne" denen odalarda çalışırdı.' },
{ id:'g18', bas:'Bir Arı Ne Kadar Bal Yapar?',
  ic:'Bir işçi arı ömrü boyunca ne kadar bal üretir?',
  cevap:'Yaklaşık bir çay kaşığının onda biri kadar. Bir kavanoz bal için binlerce arının ve milyonlarca çiçek ziyaretinin emeği vardır.' },
{ id:'g19', bas:'Kalem mi Yazı mı Önce?',
  ic:'Yazının icadı yaklaşık kaç yıl öncesine dayanır?',
  cevap:'Yaklaşık 5.000 yıl. Mezopotamya\'da çivi yazısı, Mısır\'da hiyeroglif aynı dönemlerde ortaya çıktı. İnsanlık tarihinin büyük kısmı yazısızdır; "tarih" de zaten yazıyla başlatılır.' },
{ id:'g20', bas:'Deniz Suyu Neden Tuzlu?',
  ic:'Yağmur tatlı su. Peki denizler neden tuzlu?',
  cevap:'Yağmur kayalardaki mineralleri çözüp nehirlerle denize taşır. Su buharlaşıp gider, tuz kalır; milyonlarca yılda birikir. Kapalı havzalarda bu birikim daha da artar — Lut Gölü bu yüzden çok tuzludur.' },
{ id:'g21', bas:'Endülüs\'te Ne Vardı?',
  ic:'Bugünkü İspanya topraklarında yüzyıllarca süren Endülüs medeniyetinden geriye ne kaldı?',
  cevap:'Kurtuba (Córdoba) Ulu Camii, Gırnata\'daki Elhamra Sarayı ve İşbiliye (Sevilla) Giralda\'sı ayakta. İspanyolcada binlerce Arapça kökenli kelime vardır: "ojalá" (inşallah), "azúcar" (şeker), "aceite" (zeytinyağı).' },
{ id:'g22', bas:'Kuş Neden V Uçar?',
  ic:'Göçmen kuşlar neden V şeklinde uçar?',
  cevap:'Öndeki kuşun kanat ucunda oluşan hava akımı arkadakini yukarı taşır; böylece daha az enerji harcarlar. En öndeki en çok yorulduğu için kuşlar sırayla yer değiştirir.' },
{ id:'g23', bas:'Bir Bulutun Ağırlığı',
  ic:'Gökyüzündeki orta boy beyaz bir bulut yaklaşık kaç kilo gelir?',
  cevap:'Yüzlerce ton. Ama su damlacıkları çok küçük olduğu ve yükselen hava akımıyla taşındığı için düşmez — tıpkı suda asılı kalan toz gibi.' },
{ id:'g24', bas:'Cebir Kitabının Adı',
  ic:'"Algebra" kelimesi hangi kitaptan geliyor?',
  cevap:'Hârizmî\'nin "Kitâbü\'l-muhtasar fî hisâbi\'l-cebr ve\'l-mukābele" adlı eserinden. "el-cebr" = kırığı yerine oturtmak, denklemi düzeltmek. Kelime Latinceye "algebra" olarak geçti.' },
{ id:'g25', bas:'Dilin Kaç Kelimesi Yeter?',
  ic:'Günlük konuşmada kaç kelime kullanırız?',
  cevap:'Günlük konuşmanın büyük kısmı birkaç bin kelimeyle döner; bir dilde en sık kullanılan 1.000 kelime, günlük metinlerin çok büyük bölümünü karşılar. Yeni dil öğrenirken önce sık kelimeleri öğrenmek bu yüzden hızlı ilerletir.' },
{ id:'g26', bas:'Kedi mi Köpek mi Daha İyi Duyar?',
  ic:'Kediler insanın duyamadığı sesleri duyabilir mi?',
  cevap:'Evet. İnsan yaklaşık 20 kHz\'e kadar duyar; kediler 60 kHz civarına kadar çıkar, köpekler de insandan geniş bir aralığı duyar. Kemirgenlerin çıkardığı yüksek frekanslı sesleri bu yüzden fark ederler.' },
{ id:'g27', bas:'Hat Sanatı Neden Doğdu?',
  ic:'İslam medeniyetinde yazı neden bir sanata dönüştü?',
  cevap:'Kur\'an\'ın güzel yazılması isteği yazıyı sanata taşıdı. Sülüs, nesih, talik, kûfî gibi yazı çeşitleri gelişti; hattatlar yıllarca meşk ederek "icazet" alırdı. Bir harfin ölçüsü, kalemin kendi kalınlığıyla (nokta) hesaplanır.' },
{ id:'g28', bas:'Baharat Yolu',
  ic:'Ortaçağda baharat neden bu kadar değerliydi?',
  cevap:'Uzak Doğu\'dan geldiği için taşıması zordu; yiyeceği korumaya ve tat vermeye yarardı. Karabiber bir dönem altınla kıyaslanacak kadar pahalıydı. Deniz yolu arayışı, coğrafi keşiflerin ana sebeplerinden biridir.' },
{ id:'g29', bas:'Bir Gün Hep 24 Saat miydi?',
  ic:'Dünya\'nın dönüşü hep aynı hızda mıydı?',
  cevap:'Hayır. Yaklaşık 400 milyon yıl önce bir gün 22 saat kadardı. Ay\'ın gelgit etkisiyle Dünya\'nın dönüşü çok yavaş yavaş frenleniyor; gün gitgide uzuyor.' },
{ id:'g30', bas:'Beynin Enerjisi',
  ic:'Beyin vücut ağırlığının yaklaşık %2\'si. Peki enerjinin ne kadarını kullanır?',
  cevap:'Yaklaşık %20\'sini. Düşünmek gerçekten yorucudur; dinlenirken bile beyin durmaz ve enerji tüketir.' },
{ id:'g31', bas:'Rüzgâr Gülü ve Değirmen',
  ic:'İlk yel değirmenlerinin nerede kullanıldığı biliniyor?',
  cevap:'Bilinen ilk örnekler İran-Afganistan bölgesinde (Sicistan) kullanılan dikey eksenli değirmenlerdir; tahıl öğütmek ve su çekmek için çalışırlardı. Avrupa\'daki yatay eksenli değirmenler daha sonra yaygınlaştı.' },
{ id:'g32', bas:'Deniz Kabuğunda Deniz Sesi',
  ic:'Deniz kabuğunu kulağımıza tuttuğumuzda duyduğumuz ses gerçekten deniz mi?',
  cevap:'Hayır. Duyduğumuz, çevredeki seslerin kabuğun boşluğunda yankılanmasıdır. Boş bir bardağı kulağınıza tutsanız benzer bir uğultu duyarsınız.' },
{ id:'g33', bas:'En Çok Konuşulan Diller',
  ic:'Dünyada ana dili olarak en çok konuşulan diller hangileri?',
  cevap:'Ana dili sayısında Çince (Mandarin), İspanyolca, İngilizce, Hintçe ve Arapça ilk sıralarda yer alır. Toplam konuşur sayısında ise ikinci dil olarak öğrenenler yüzünden İngilizce başa geçer.' },
{ id:'g34', bas:'Tuz Neden Buzu Eritir?',
  ic:'Kışın yollara tuz atılır. Bilimsel sebebi ne?',
  cevap:'Tuz suyun donma noktasını düşürür. Saf su 0 °C\'de donarken tuzlu su daha düşük sıcaklıkta donar; böylece yoldaki buz erir ve yeniden donması zorlaşır.' },
{ id:'g35', bas:'Kütüphanelerin Atası',
  ic:'Ortaçağ İslam dünyasında kitapların toplandığı kurumlara ne denirdi?',
  cevap:'"Beytü\'l-hikme" (Hikmet Evi) ve "dârülkütüb" gibi adlar kullanılırdı. Bağdat\'taki Beytü\'l-hikme\'de Yunanca, Farsça ve Sanskritçe eserler Arapçaya çevrildi; bu çeviriler daha sonra Avrupa\'ya Latince yoluyla ulaştı.' },
{ id:'g36', bas:'Renk Körlüğü Ne Kadar Yaygın?',
  ic:'Sınıfta renkleri farklı gören biri olabilir mi?',
  cevap:'Olabilir. Kırmızı-yeşil renk körlüğü erkeklerde yaklaşık %8, kadınlarda %0,5 civarında görülür. Bu yüzden tahtada yalnız renkle ayrım yapmak yerine şekil ya da yazıyla da belirtmek iyi olur.' }
],

/* ══════════════════════════════════════════════════ 4) BULMACA (36) */
bulmaca: [
{ id:'b01', bas:'Sessiz Konuşan',
  ic:'Ağzı yok ama konuşur, kulağı yok ama dinletir. Kapağını açan onun sesini duyar. Nedir?',
  cevap:'Kitap.' },
{ id:'b02', bas:'Hep Önünde',
  ic:'Sana ait ama onu en çok başkaları kullanır. Nedir?',
  cevap:'Adın.' },
{ id:'b03', bas:'Yükseldikçe Azalır',
  ic:'Ne kadar çok alırsan o kadar çok geride bırakırsın. Nedir?',
  cevap:'Adım.' },
{ id:'b04', bas:'Peşinden Gelen',
  ic:'Güneşte peşini bırakmaz, karanlıkta yok olur. Dokunamazsın ama hep oradadır. Nedir?',
  cevap:'Gölge.' },
{ id:'b05', bas:'Verince Çoğalan',
  ic:'Ne kadar verirsen o kadar çoğalır; sakladıkça azalır. Nedir?',
  cevap:'Bilgi.' },
{ id:'b06', bas:'İki Baba İki Oğul',
  ic:'İki baba ve iki oğul bir arabaya biniyor ama arabada sadece üç kişi var. Nasıl olur?',
  cevap:'Dede, baba ve oğul. Ortadaki kişi hem baba hem oğuldur.' },
{ id:'b07', bas:'Yanan Mum',
  ic:'Odada beş mum yanıyor. Rüzgâr esti, ikisi söndü. Sabah odaya girdiğinde kaç mum bulursun?',
  cevap:'İki. Yanmaya devam eden üçü eriyip bitmiştir; sönenler kalmıştır.' },
{ id:'b08', bas:'Hep Dolu Hiç Dolmaz',
  ic:'Ne kadar doldurursan doldur boşalmaz, boşalttıkça büyür. Nedir?',
  cevap:'Çukur.' },
{ id:'b09', bas:'Dünya Turu',
  ic:'Dünyayı dolaşır ama hep aynı köşede durur. Nedir?',
  cevap:'Pul.' },
{ id:'b10', bas:'Dilsiz Öğretmen',
  ic:'Sorunu sorar, cevabı vermez; ama yanlış yaparsan hemen gösterir. Nedir?',
  cevap:'Ayna.' },
{ id:'b11', bas:'Kaç Kardeş?',
  ic:'Bir ailede her ERKEK çocuğun kız kardeş sayısı, erkek kardeş sayısına eşit. Her KIZ çocuğun kız kardeş sayısı ise erkek kardeş sayısının yarısı kadar. Bu ailede kaç çocuk var?',
  cevap:'7 çocuk: 4 erkek, 3 kız. Kontrol: bir erkeğin 3 erkek, 3 kız kardeşi vardır — eşit. Bir kızın 2 kız, 4 erkek kardeşi vardır — kız sayısı erkeğin yarısı.' },
{ id:'b12', bas:'Ne Kadar Toprak?',
  ic:'2 metre eninde, 3 metre boyunda, 1 metre derinliğinde bir çukurda ne kadar toprak vardır?',
  cevap:'Hiç. Çukur boştur; toprak olsaydı çukur olmazdı.' },
{ id:'b13', bas:'Yaşı Kaç?',
  ic:'Ahmet\'e yaşı soruldu: «İki yıl sonraki yaşımın iki katından, iki yıl önceki yaşımın iki katını çıkarırsan yaşımı bulursun.» Ahmet kaç yaşında?',
  cevap:'8. İşlem: 2(x+2) − 2(x−2) = 2x+4 − 2x+4 = 8. Sonuç x\'ten bağımsız, hep 8 çıkar; yani Ahmet yaşını dolaylı yoldan doğrudan söylemiş oldu.' },
{ id:'b14', bas:'Yalancı Köy',
  ic:'İki yol var: biri şehre, biri çöle gidiyor. Kavşakta iki kişi duruyor; biri hep doğru, biri hep yalan söylüyor ama hangisinin hangisi olduğunu bilmiyorsun. TEK bir soruyla şehrin yolunu nasıl bulursun?',
  cevap:'Birine sor: «Öteki kişiye şehrin yolunu sorsam hangi yolu gösterirdi?» Gösterdiği yolun TERSİNE git. Çünkü iki durumda da cevap yanlış yolu gösterir.' },
{ id:'b15', bas:'Ağırlık Tahmini',
  ic:'Bir kilo demir mi daha ağırdır, bir kilo pamuk mu?',
  cevap:'İkisi de bir kilo, eşittir. Fark ağırlıkta değil hacimdedir: pamuk çok daha fazla yer kaplar.' },
{ id:'b16', bas:'Altı Bardak',
  ic:'Sırada DOLU-DOLU-DOLU-BOŞ-BOŞ-BOŞ diye altı bardak duruyor. Tek bir bardağa dokunarak dizilişi DOLU-BOŞ-DOLU-BOŞ-DOLU-BOŞ yapabilir misin?',
  cevap:'Evet: 2. bardağı kaldır, içindekini 5. bardağa boşalt, boş bardağı yerine koy. Bardakların yeri değişmedi ama diziliş dolu-boş-dolu-boş-dolu-boş oldu.' },
{ id:'b17', bas:'Tersten de Anlamlı',
  ic:'Türkçede bazı kelimeler tersten okununca da anlamlıdır: KAR ↔ RAK, KAZ ↔ ZAK… Sınıfça üç harfli kaç çift bulabilirsiniz?',
  cevap:'Örnekler: KAR–RAK, KAÇ–ÇAK, TAS–SAT, ÇAM–MAÇ, KİM–MİK, NAR–RAN, TOK–KOT, ÇİT–TİÇ (yok), KAP–PAK, SAÇ–ÇAS (yok). Geçerli olanları tahtaya yazın; anlamını söyleyemeyen çift sayılmaz.' },
{ id:'b18', bas:'Hangi Ay?',
  ic:'Hangi ayda 28 gün vardır?',
  cevap:'Hepsinde. Her ayın en az 28 günü vardır.' },
{ id:'b19', bas:'Doktor ve Çocuk',
  ic:'Baba ve oğlu kaza geçirir, hastaneye götürülürler. Doktor çocuğu görünce «Ben bu çocuğu ameliyat edemem, o benim oğlum» der. Nasıl olur?',
  cevap:'Doktor çocuğun annesidir.' },
{ id:'b20', bas:'Kibrit ve Karanlık Oda',
  ic:'Karanlık bir odaya girdin. Elinde bir kibrit var; odada bir gaz lambası, bir mum ve bir soba var. Önce neyi yakarsın?',
  cevap:'Kibriti.' },
{ id:'b21', bas:'Üç Anahtar',
  ic:'Üç kapalı kutu var: birinde elma, birinde armut, birinde ikisi de. Üçünün de etiketi YANLIŞ. Bir kutudan tek bir meyve çekerek hepsini doğru etiketleyebilir misin?',
  cevap:'Evet: "karışık" etiketli kutudan çek. Ne çıkarsa kutu odur (etiketi yanlış olduğu için karışık olamaz). Sonra kalan ikisi zincirleme olarak çözülür.' },
{ id:'b22', bas:'Zaman Bilmecesi',
  ic:'Bir tren saat 09:00\'da kalkıp 3 saat yol gidiyor. Ama vardığında saat 11:00. Nasıl olur?',
  cevap:'Saat dilimi değişmiştir (bir saat geri). Ya da yaz saati uygulaması bitmiştir.' },
{ id:'b23', bas:'Kaç Kere Kesilir?',
  ic:'Bir ipi 4 parçaya bölmek için kaç kez kesmek gerekir?',
  cevap:'3 kez.' },
{ id:'b24', bas:'Üç Lamba',
  ic:'Kapalı bir odada üç lamba var, dışarıda üç düğme. Odaya sadece BİR kez girebilirsin. Hangi düğmenin hangi lambaya ait olduğunu nasıl bulursun?',
  cevap:'Birinci düğmeyi aç, beş dakika bekle, kapat. İkinciyi aç, odaya gir. Yanan = ikinci. Sönük ama SICAK = birinci. Sönük ve soğuk = üçüncü.' },
{ id:'b25', bas:'Nehri Geçmek',
  ic:'Çiftçi; kurt, keçi ve lahanayı karşıya geçirecek. Kayığa kendisiyle beraber yalnız biri sığıyor. Kurt keçiyle, keçi lahanayla yalnız kalmamalı. Nasıl geçirir?',
  cevap:'Önce keçiyi geçirir, döner. Kurdu geçirir, keçiyi geri getirir. Lahanayı geçirir, döner. Son olarak keçiyi geçirir.' },
{ id:'b26', bas:'Merdivendeki Adam',
  ic:'Bir kişi 10 katlı binanın en üstünde oturuyor. Her sabah asansörle zemine iniyor. Akşam dönerken yalnız yağmurlu günlerde 10. kata kadar çıkabiliyor, diğer günler 7. katta inip yürüyor. Neden?',
  cevap:'Boyu 10. katın düğmesine yetmiyor; yağmurlu günlerde şemsiyesiyle düğmeye basabiliyor.' },
{ id:'b27', bas:'Sayı Dizisi',
  ic:'1, 11, 21, 1211, 111221, … Sıradaki sayı nedir?',
  cevap:'312211. Her satır bir öncekini OKUR: "bir bir" → 11, "iki bir" → 21, "bir iki bir bir" → 1211… Buna "bak ve söyle" dizisi denir.' },
{ id:'b28', bas:'Otobüs Ne Yana Gidiyor?',
  ic:'Bir otobüsün yandan çekilmiş resmine bakıyorsun; hiçbir kapı görünmüyor. Otobüs sağa mı sola mı gidiyor?',
  cevap:'SOLA. Trafiğin sağdan aktığı ülkelerde kapılar otobüsün sağ yanındadır. Kapıları göremiyorsan otobüsün SOL yanına bakıyorsundur; bu da önünün sola dönük olduğu anlamına gelir.' },
{ id:'b29', bas:'Terazi ve Dokuz Bilye',
  ic:'Dokuz bilyeden biri ötekilerden ağır. Eşit kollu teraziyle EN AZ kaç tartımda bulursun?',
  cevap:'2 tartım. Üçerli üç gruba ayır, ikisini tart: ağır grup belli olur (denge olursa üçüncü grup). Sonra o gruptan iki bilyeyi tart.' },
{ id:'b30', bas:'Eriyen Kelime',
  ic:'Beş harfli bir kelime düşünün: sondan birer harf attıkça geriye hep anlamlı bir kelime kalsın. Bulabilir misiniz?',
  cevap:'KARAR → KARA → KAR → AR. Dördü de anlamlı. Başka zincirler: SATIR → SATI → SAT, KALEM → KALE → KAL.' },
{ id:'b31', bas:'İki Kum Saati',
  ic:'Elinde 4 dakikalık ve 7 dakikalık iki kum saati var. Tam 9 dakikayı nasıl ölçersin?',
  cevap:'İkisini birlikte başlat. 4. dakikada 4\'lük biter, ÇEVİR. 7. dakikada 7\'lik biter, onu da ÇEVİR. 8. dakikada 4\'lük yine biter; o anda 7\'lik daha 1 dakikadır dönüyordur, yani altında 1 dakikalık kum vardır. 7\'liği ÇEVİR: o kum 1 dakikada akar ve tam 9. dakika dolar.' },
{ id:'b32', bas:'Yaş Farkı',
  ic:'Bugün babanın yaşı oğlunun yaşının 4 katı. 20 yıl sonra 2 katı olacak. Bugün kaç yaşındalar?',
  cevap:'Oğul 10, baba 40. (4x + 20 = 2(x + 20) → 4x + 20 = 2x + 40 → x = 10.)' },
{ id:'b33', bas:'Bir Kelime, İki Anlam',
  ic:'Hem "yüzmek" fiili hem de "yüz" sayısı, hem de insanın yüzü… Türkçede aynı yazılan farklı anlamlı kelimelere ne denir?',
  cevap:'Sesteş (eş sesli) kelime. Arapçada da benzeri vardır: harekesiz yazılan bir kelime birkaç şekilde okunabilir; bağlam (siyak) doğru okumayı belirler.' },
{ id:'b34', bas:'Kayıp Lira',
  ic:'Üç kişi 30 lira ödeyip odaya çıkar. Görevli 5 lira fazla alındığını fark edip geri gönderir; getiren 2 lirayı cebine atar, 3 lirayı dağıtır. Herkes 9 lira ödedi: 27 + cepteki 2 = 29. Bir lira nerede?',
  cevap:'Hiçbir yerde kaybolmadı; hesap yanlış kuruldu. Doğrusu 27 = 25 (oda) + 2 (cep). Cepteki 2 liranın 27\'ye eklenmesi değil, içinden çıkarılması gerekir.' },
{ id:'b35', bas:'Karanlıkta Çorap',
  ic:'Karanlık bir çekmecede karışık hâlde 10 siyah, 10 lacivert çorap var. Işığı açmadan, AYNI RENKTEN bir çift garantilemek için en az kaç tek çorap çekmelisin?',
  cevap:'3. İkisini çekersen renkleri farklı olabilir; üçüncüde mutlaka bir renk tekrar eder.' },
{ id:'b36', bas:'Köprüden Geçiş',
  ic:'Dört kişi gece köprüden geçecek. Tek fenerleri var, köprüden aynı anda en çok iki kişi geçebiliyor ve fener hep yanlarında olmalı. Geçiş süreleri 1, 2, 5 ve 10 dakika; birlikte geçenler yavaş olanın süresinde geçer. En kısa toplam süre kaçtır?',
  cevap:'17 dakika. 1 ve 2 geçer (2), 1 döner (1), 5 ve 10 geçer (10), 2 döner (2), 1 ve 2 geçer (2). Toplam 2+1+10+2+2 = 17.' }
]
};
