/* SÖZLÜK DİZİNİ — sitenin kendi verisinden "yüzey biçim → aranan yalın
   biçim + tür" haritası çıkarır.                (sozluk/dizin_uret.js)
   ---------------------------------------------------------------------
   Sözlük simülasyonu her kelime için "sözlükte ARANAN yalın biçimi"
   ister; bu betik onu ELLE yazmak yerine sitenin var olan üç verisinden
   türetir:

     veri/veri_kokler.js  -> wordEasterEggs  (kök veritabanı; adı eski,
                             içi 500+ kökün bütün kalıpları)
     veri/veri_sozluk.js  -> sozlukVerileri  (câmid/sözlük kayıtları:
                             "İsim: Hadise", "Zarf: Altında" …)
     veri/veri_vezin_numaralari.js -> KALIP_DATA (kalıp no → "… Mazi"/
                             "… Muzari"/"… Emir"/"… Mastar" …)

   ARANAN BİÇİM KURALI (sözlük simülasyonunun kendi kuralı):
     • Mazi              -> kendisi            (كَتَبَ   → كتب)
     • Muzari / Emir     -> KENDİ BABININ mazisi (يُفَضِّلُ → فضل,
                            أَعْطِني → أعطى)  — kalıp numarasından bulunur
     • Mastar / İsm-i Fâil / İsm-i Mef'ûl / isim kalıpları
                         -> kendisi            (كِتاب → كتاب, مُعَلِّم → معلم)
     • câmid sözlük kaydı-> hücrenin tekil base'i (çoğul da oraya bakar)

   Çıktı (stdout, JSON):
     { "<harekesiz yüzey>": [ {ara, tur, kalip, rol, rk, ek, mu} … ] }
   Aynı biçim birden çok yerde geçebilir; seçimi çözümleyici yapar.     */
const fs = require('fs'), vm = require('vm');

/* node <betik> <kok> çağrısında argv[2] ilk argümandır. */
const KOK = process.argv[2] || '.';
const ctx = { window: {}, console, document: { getElementById: () => null } };
ctx.window = ctx;
vm.createContext(ctx);

function oku(yol, son) {
    return vm.runInContext(fs.readFileSync(KOK + '/' + yol, 'utf8') + '\n;' + son, ctx);
}
const KOKLER = oku('veri/veri_kokler.js',
    '(typeof wordEasterEggs !== "undefined" ? wordEasterEggs : null)');
const SOZLUK = oku('veri/veri_sozluk.js',
    '(typeof sozlukVerileri !== "undefined" ? sozlukVerileri : null)');
const KALIP = oku('veri/veri_vezin_numaralari.js',
    '(typeof KALIP_DATA !== "undefined" ? KALIP_DATA : null)');
if (!KOKLER || !SOZLUK || !KALIP) { console.error('veri okunamadı'); process.exit(2); }

const OZEL = { base: 1, ornek: 1, cekimi: 1, suggestsPlus: 1, tip: 1,
               isDictOnly: 1, cogulId: 1, tekilId: 1, autoGenerated: 1 };
const RE_HAREKE = /[ً-ْٰـ]/g;
const RE_TEMIZ = /[^ء-ي ]/g;
function yal(s) {
    return String(s == null ? '' : s).replace(RE_HAREKE, '').replace(RE_TEMIZ, '').trim();
}

/* Kalıbın rolü: KALIP_DATA'nın Türkçe adından okunur. */
function rol(k) {
    var t = (KALIP[k] && KALIP[k].tr) || '';
    if (/Mazi/i.test(t)) return 'mazi';
    if (/Muzari/i.test(t)) return 'muzari';
    if (/Emir/i.test(t)) return 'emir';
    if (/Mastar/i.test(t)) return 'mastar';
    if (/İsm-i Fail|Ism-i Fail/i.test(t)) return 'fail';
    if (/İsm-i Meful|Ism-i Meful/i.test(t)) return 'meful';
    return 'isim';
}
/* Mücerret mi mezid mi — kalıp numarası 52'den itibaren mezid. */
function mezidMi(k) { return parseInt(k, 10) >= 52; }

const dizin = {};
function koy(anahtar, kayit) {
    if (!anahtar) return;
    var l = (dizin[anahtar] = dizin[anahtar] || []);
    /* Aynı (ara,tur) ikilisi iki kez yazılmasın. */
    for (var i = 0; i < l.length; i++)
        if (l[i].ara === kayit.ara && l[i].rol === kayit.rol) return;
    l.push(kayit);
}

/* Aday sıralaması: aynı biçim hem fiil hücresinde hem sayısal bir isim
   hücresinde geçebiliyor (يكتب). Önce ROLÜ belli olanlar gelsin ki
   çözümleyici ilkini alabilsin. */
var ROL_ONCELIK = { mazi: 1, muzari: 1, emir: 1, mastar: 2, fail: 2, meful: 2,
                    tekil: 2, coguldan: 2, isim: 3 };
function sirala() {
    Object.keys(dizin).forEach(function (k) {
        dizin[k].sort(function (a, b) {
            return (ROL_ONCELIK[a.rol] || 9) - (ROL_ONCELIK[b.rol] || 9);
        });
    });
}

/* ---------------------------------------------------------------- 1) KÖKLER */
Object.keys(KOKLER).forEach(function (rk) {
    var rd = KOKLER[rk];
    if (!rd || typeof rd !== 'object') return;
    var nolar = Object.keys(rd).filter(function (k) { return /^\d+$/.test(k); })
                               .map(Number).sort(function (a, b) { return a - b; });

    /* Her bab için mazi kalıbı: kendinden küçük EN BÜYÜK mazi. */
    function babMazisi(k) {
        var en = null;
        for (var i = 0; i < nolar.length; i++) {
            if (nolar[i] > k) break;
            if (rol(nolar[i]) === 'mazi') en = nolar[i];
        }
        return en;
    }

    nolar.forEach(function (k) {
        var hucre = rd[k];
        if (!hucre || !hucre.base || !hucre.base.arText) return;
        var r = rol(k), kendi = yal(hucre.base.arText);
        if (!kendi) return;

        var ara = kendi;
        if (r === 'muzari' || r === 'emir') {
            var m = babMazisi(k);
            var mz = (m != null && rd[m] && rd[m].base) ? yal(rd[m].base.arText) : '';
            /* Mücerret fiilde mazi = kökün kendisi; mazi hücresi yoksa
               köke düş (يَذْهَبُ → ذهب). */
            ara = mz || (mezidMi(k) ? kendi : yal(rk));
        }
        var tur = (r === 'mazi' || r === 'muzari' || r === 'emir') ? 'fiil' : 'isim';
        var ortak = { ara: ara, tur: tur, kalip: k, rol: r, rk: rk,
                      mezid: mezidMi(k) ? 1 : 0 };

        koy(kendi, ortak);
        if (hucre.base.muennes) koy(yal(hucre.base.muennes), Object.assign({ mu: 1 }, ortak));

        Object.keys(hucre).forEach(function (sfx) {
            if (OZEL[sfx]) return;
            var sd = hucre[sfx];
            if (!sd || !sd.arText) return;
            var y = yal(sd.arText);
            if (!y || y === kendi) return;
            koy(y, Object.assign({ ek: sfx }, ortak));
            if (sd.muennes) koy(yal(sd.muennes), Object.assign({ ek: sfx, mu: 1 }, ortak));
        });
    });
});

/* ------------------------------------------------------------- 2) CÂMİDLER */
/* Anahtar öneki türü söylüyor: "Zarf: Altında" → zarf, "Soru: Nerede"
   → soru, "Şehir: …" → özel ad (aranmaz). */
var ONEK_TUR = {
    'Zarf': 'zarf', 'Zaman': 'zarf', 'Yön': 'zarf',
    'Edat': 'edat', 'Harficer': 'edat', 'Bağlaç': 'edat', 'Soru': 'edat',
    'Cevap': 'edat', 'Kalıp': 'ifade',
    'Zamir': 'SKIP', 'İşaret': 'SKIP', 'Mevsul': 'SKIP',
    'Şehir': 'SKIP', 'Ülke': 'SKIP', 'Kıta': 'SKIP'
};

Object.keys(SOZLUK).forEach(function (rk) {
    var d = SOZLUK[rk];
    if (!d || typeof d !== 'object') return;
    /* KÖK anahtarları (ت ر ك gibi saf Arapça) burada İŞLENMEZ: onlar
       zaten KOKLER geçişinde, kalıp numarasıyla ve doğru rolüyle
       dizine girdi. Burada ikinci kez işlenince rolü "5" gibi ham bir
       numara olan ikiz kayıtlar çıkıyor ve اِغْسِلْ emri "isim" diye
       çözülüyordu. Yalnız sözlük kayıtları (anahtarında ':' olan ya da
       isDictOnly işaretli) alınır. */
    if (rk.indexOf(':') < 0 && !d.isDictOnly) return;
    var m = /^([^:]+):/.exec(rk);
    var onek = m ? m[1].trim() : '';
    var tur = ONEK_TUR[onek] || 'isim';

    Object.keys(d).forEach(function (hk) {
        if (hk === 'isDictOnly' || hk === 'tip') return;
        var hucre = d[hk];
        /* "cogul": "حَوَادِث" gibi düz dizge alanlar: tekil base'e bağlanır */
        if (typeof hucre === 'string') {
            var tekil = d.tekil && d.tekil.base ? yal(d.tekil.base.arText) : '';
            if (tekil && /cogul|cemi/i.test(hk))
                koy(yal(hucre), { ara: tekil, tur: tur, rol: 'coguldan', rk: rk, ek: hk, onek: onek });
            return;
        }
        if (!hucre || typeof hucre !== 'object') return;
        if (!hucre.base || !hucre.base.arText) return;
        var kendi = yal(hucre.base.arText);
        if (!kendi) return;
        /* Câmid kayıtta aranan biçim TEKİL base'dir; başka hücreler
           (çoğul, nispet…) de oraya götürür. */
        var tekilBase = (d.tekil && d.tekil.base) ? yal(d.tekil.base.arText) : kendi;
        var ara = (tur === 'SKIP') ? 'SKIP' : (tekilBase || kendi);
        var ortak = { ara: ara, tur: tur, rol: (hk === 'tekil' ? 'tekil' : hk),
                      rk: rk, onek: onek };
        koy(kendi, ortak);
        if (hucre.base.muennes) koy(yal(hucre.base.muennes), Object.assign({ mu: 1 }, ortak));
        Object.keys(hucre).forEach(function (sfx) {
            if (OZEL[sfx]) return;
            var sd = hucre[sfx];
            if (!sd || !sd.arText) return;
            var y = yal(sd.arText);
            if (!y || y === kendi) return;
            koy(y, Object.assign({ ek: sfx }, ortak));
        });
    });
});

sirala();
process.stdout.write(JSON.stringify(dizin));
