/* =========================================================================
   KİDEF — SÖZLÜK MOTORU            (sozluk.html + index'teki açılır sözlük)
   -------------------------------------------------------------------------
   NE YAPAR: veri/veri_sozluk.js içindeki sözlüğü arar ve sonuçları basar.
   Vezinler tablosundaki sözlük paneliyle AYNI VERİYİ okur; fark, burada
   yalnız sözlük olması: kök çipi yok, "vezinlere bak" yok, kök aranmıyor,
   tabloya atlama yok (Geylani: "tek farkı sadece sözlük kısmı olacak,
   kök bağlantısı vs olmayacak, kök aranmayacak, klavye aynı olsun").

   ARAMA KURALLARI — tablodaki panelle birebir aynı tutuldu:
     · harekeler yok sayılır      (كِتاب = كتاب)
     · أ إ آ  ->  ا  sayılır       (أكل yazınca اكل de bulunur)
     · "ال" öneki olan kelime eksiz hâliyle de eşleşir (الكتاب -> كتاب)
     · Türkçe anlam da aranır      ("kitap" yazınca كِتاب gelir)
   Dizin BİR KEZ kurulur; her tuşta baştan tarama yapılmaz.

   KLAVYE: vezinler tablosundaki düzenin aynısı (universalKeyboardLayout)
   ve aynı harf renkleri.
   ========================================================================= */
(function () {
    'use strict';

    /* ---------------- klavye (tablodakiyle aynı) ---------------- */
    var DUZEN = [
        ['ذ', 'ض', 'ص', 'ث', 'ق', 'ف', 'غ', 'ع', 'ه', 'خ', 'ح', 'ج', 'د'],
        ['ش', 'س', 'ي', 'ب', 'ل', 'ا', 'ت', 'ن', 'م', 'ك', 'ط'],
        ['ئ', 'ء', 'ؤ', 'ر', 'ى', 'ة', 'و', 'ز', 'ظ', 'BACKSPACE']
    ];
    var RENK = {
        'ب': '#d4efdf', 'ت': '#d4efdf', 'ث': '#d4efdf',
        'ج': '#fadbd8', 'ح': '#fadbd8', 'خ': '#fadbd8',
        'د': '#fae5d3', 'ذ': '#fae5d3',
        'ر': '#fcf3cf', 'ز': '#fcf3cf',
        'س': '#d6eaf8', 'ش': '#d6eaf8',
        'ص': '#e8daef', 'ض': '#e8daef',
        'ط': '#d1f2eb', 'ظ': '#d1f2eb',
        'ع': '#f5b7b1', 'غ': '#f5b7b1',
        'ف': '#d4e6f1', 'ق': '#d4e6f1',
        'ا': '#ebedef', 'ء': '#ebedef', 'ؤ': '#ebedef', 'ئ': '#ebedef',
        'ي': '#d7bde2', 'ى': '#d7bde2'
    };

    /* ---------------- normalleştirme ---------------- */
    var RE_HAREKE = /[ً-ْٰ]/g;
    var RE_HEMZE = /[أإآ]/g;
    var RE_BOSLUK = /\s+/;

    function hrk(s) { return s ? String(s).replace(RE_HAREKE, '') : ''; }
    function nrm(s) { return s ? String(s).replace(RE_HEMZE, 'ا') : ''; }
    function sade(s) { return nrm(hrk(s)); }

    /* "الكتاب" hem kendisiyle hem "كتاب" ile eşleşsin */
    function parcala(sn) {
        var ps = String(sn || '').split('/'), out = [];
        for (var i = 0; i < ps.length; i++) {
            var pt = ps[i].trim();
            out.push({ p: pt, p2: (pt.lastIndexOf('ال', 0) === 0 ? pt.substring(2) : null) });
        }
        return out;
    }

    /* ---------------- dizin ----------------
       Alan adları veri dosyasının biçimini izler: kayıt ya düz
       { word, meaning, type } ya da { base:{ arText, trText } } + ekler.
       Her iki biçim de destekleniyor — tablodaki panel de böyle okuyor. */
    var OZEL = { base: 1, ornek: 1, cekimi: 1, suggestsPlus: 1, tip: 1,
                 isDictOnly: 1, cogulId: 1, tekilId: 1, autoGenerated: 1,
                 hasZamirCekimi: 1, zamirBase: 1, isHiddenInList: 1,
                 kuralliCogul: 1, isNotVerb: 1, not: 1, emoji: 1 };

    var _dizin = null;

    function ekle(d, ar, tr, tur) {
        if (!ar || !String(ar).trim() || !tr) return;
        var sAr = hrk(ar);
        if (sAr.trim().split(RE_BOSLUK).length > 3) return;   /* cümle değil, kelime */
        d.push({
            ar: ar, tr: tr, tur: tur || '',
            sAr: sAr, pAr: parcala(nrm(sAr)),
            trl: String(tr).toLowerCase()
        });
    }

    function kur() {
        var d = [];
        var SV = (typeof sozlukVerileri !== 'undefined' && sozlukVerileri) ? sozlukVerileri : {};
        var sahip = Object.prototype.hasOwnProperty;
        for (var kok in SV) {
            if (!sahip.call(SV, kok)) continue;
            if (kok.lastIndexOf('Sayı:', 0) === 0 || kok.lastIndexOf('Sıra:', 0) === 0) continue;
            var kd0 = SV[kok];
            if (!kd0 || typeof kd0 !== 'object') continue;
            for (var kalip in kd0) {
                if (!sahip.call(kd0, kalip)) continue;
                var kd = kd0[kalip];
                if (!kd || typeof kd !== 'object') continue;
                /* düz biçim: { word, meaning, type } */
                if (kd.word) { ekle(d, kd.word, kd.meaning, kd.type); continue; }
                /* katmanlı biçim: base + ekler */
                if (kd.base && kd.base.arText) ekle(d, kd.base.arText, kd.base.trText, kd.base.tip || kd.tip);
                for (var sfx in kd) {
                    if (!sahip.call(kd, sfx) || OZEL[sfx]) continue;
                    var sd = kd[sfx];
                    if (sd && sd.arText) ekle(d, sd.arText, sd.trText, sd.tip || kd.tip);
                }
            }
        }
        _dizin = d;
        return d;
    }

    function dizin() { return _dizin || kur(); }

    /* ---------------- arama ---------------- */
    function ara(sorgu, sinir) {
        sinir = sinir || 60;
        var q = String(sorgu || '').trim();
        if (!q) return [];
        var d = dizin();
        var arapcaMi = /[؀-ۿ]/.test(q);
        var qa = sade(q);
        /* Sorguda "ال" varsa eksiz hâli de denenir: الكتاب yazan da
           كتاب'ı bulsun (kayıtlarda ters yönü zaten parcala() kuruyor). */
        var qa2 = (qa.lastIndexOf('ال', 0) === 0 && qa.length > 3) ? qa.substring(2) : null;
        var qt = q.toLocaleLowerCase('tr-TR');
        var tam = [], bas = [], ic = [], n = 0;

        for (var i = 0; i < d.length && n < sinir * 3; i++) {
            var o = d[i], puan = -1;
            if (arapcaMi) {
                for (var j = 0; j < o.pAr.length; j++) {
                    var p = o.pAr[j].p, p2 = o.pAr[j].p2;
                    if (p === qa || p2 === qa || (qa2 && (p === qa2 || p2 === qa2))) { puan = 0; break; }
                    if (p.lastIndexOf(qa, 0) === 0 || (p2 && p2.lastIndexOf(qa, 0) === 0) ||
                        (qa2 && (p.lastIndexOf(qa2, 0) === 0 || (p2 && p2.lastIndexOf(qa2, 0) === 0)))) { puan = 1; break; }
                    if (p.indexOf(qa) > 0) puan = 2;
                }
            } else {
                var t = o.trl;
                if (t === qt) puan = 0;
                else {
                    var kel = t.split(/[ \/.,()]+/);
                    if (kel.indexOf(qt) >= 0) puan = 0;
                    else if (t.lastIndexOf(qt, 0) === 0) puan = 1;
                    else if (t.indexOf(qt) > 0) puan = 2;
                }
            }
            if (puan < 0) continue;
            n++;
            (puan === 0 ? tam : puan === 1 ? bas : ic).push(o);
        }
        return tam.concat(bas, ic).slice(0, sinir);
    }

    /* ---------------- çizim ---------------- */
    function kacir(s) {
        return String(s == null ? '' : s)
            .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    /* ---------------- klavye boyutu ----------------
       İKİ BOYUT (Geylani: "iki farklı klavye boyutu olsun, biri tam diğeri
       yatay olarak daha küçük olsun ama harfleri çok küçültmeden"):
         TAM — tuşlar ekranın enine yayılır. Tahtaya yansıtıldığında en
               okunaklısı.
         DAR — klavye yatayda toplanır; tuşlar dar ama YÜKSEKLİK aynı kalır
               ve harf ancak bir tık küçülür. Parmak az yol gittiği için
               dokunarak yazmak kolaylaşır.
       Seçim hatırlanır. Boşluk çubuğunun yanındaki tuş değiştirir; ölçüler
       sozluk.html'deki --klv-dar'da. Dar seçenek yalnız geniş ekranda var:
       telefonda klavye zaten dar, daha da daraltmak tuşu küçültürdü. */
    var KLV_ANAHTAR = 'kidef_sozluk_klavye';
    function klvOku() {
        try { return localStorage.getItem(KLV_ANAHTAR) === 'dar' ? 'dar' : 'tam'; }
        catch (e) { return 'tam'; }
    }
    function klvYaz(v) { try { localStorage.setItem(KLV_ANAHTAR, v); } catch (e) { } }

    var BOYUT_IK =
        '<svg class="szk-bik" viewBox="0 0 24 24" fill="none" stroke="currentColor"' +
        ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
        '<path d="M12 6.5v11" opacity=".5"/>' +
        '<g class="bi-ic"><path d="M4 12h5"/><path d="M6.6 9.4 9.2 12 6.6 14.6"/>' +
        '<path d="M20 12h-5"/><path d="M17.4 9.4 14.8 12 17.4 14.6"/></g>' +
        '<g class="bi-dis"><path d="M9 12H4"/><path d="M6.6 9.4 4 12 6.6 14.6"/>' +
        '<path d="M15 12h5"/><path d="M17.4 9.4 20 12 17.4 14.6"/></g></svg>';

    function boyutUygula(kap, mod) {
        var dar = mod === 'dar';
        kap.classList.toggle('dar', dar);
        var t = kap.querySelector('.szk-boyut');
        if (!t) return;
        t.setAttribute('aria-pressed', dar ? 'true' : 'false');
        t.setAttribute('title', dar ? 'Klavyeyi genişlet (tam boy)'
                                    : 'Klavyeyi daralt — dokunarak yazmak kolaylaşır');
        var ad = t.querySelector('.szk-boyutad');
        if (ad) ad.textContent = dar ? 'Tam' : 'Dar';
    }

    function klavyeCiz(kap, yaz, sil) {
        if (!kap) return;
        var h = '';
        DUZEN.forEach(function (satir) {
            h += '<div class="szk-satir">';
            satir.forEach(function (c) {
                if (c === 'BACKSPACE') {
                    h += '<button type="button" class="szk-tus szk-sil" data-sil="1" aria-label="Sil">⌫</button>';
                } else {
                    var g = c === 'ه' ? 'هـ' : c;
                    h += '<button type="button" class="szk-tus" data-h="' + c + '"' +
                         ' style="--szk-bg:' + (RENK[c] || '#fff') + '">' + g + '</button>';
                }
            });
            h += '</div>';
        });
        h += '<div class="szk-satir">' +
               '<button type="button" class="szk-tus szk-bosluk" data-h=" " aria-label="Boşluk"></button>' +
               '<button type="button" class="szk-boyut" data-boyut="1" aria-pressed="false">' +
                 BOYUT_IK + '<span class="szk-boyutad">Dar</span></button>' +
             '</div>';
        kap.innerHTML = h;
        boyutUygula(kap, klvOku());
        kap.addEventListener('click', function (e) {
            if (!e.target.closest) return;
            var b = e.target.closest('.szk-boyut');
            if (b) {
                var yeni = kap.classList.contains('dar') ? 'tam' : 'dar';
                klvYaz(yeni); boyutUygula(kap, yeni);
                return;
            }
            var t = e.target.closest('.szk-tus');
            if (!t) return;
            if (t.hasAttribute('data-sil')) sil();
            else yaz(t.getAttribute('data-h'));
        });
    }

    /* Yıldız — öğrenci kelimeyi favorilerine alır (sarf/sozlukfavori.js).
       Boşken çizgi, doluyken altın. Kart hem aramada hem "Favorilerim"
       listesinde aynı biçimde çizilsin diye tek yerden üretiliyor. */
    var YILDIZ =
        '<svg viewBox="0 0 24 24" aria-hidden="true">' +
        '<path d="M12 3.4l2.65 5.37 5.93.86-4.29 4.18 1.01 5.9L12 16.92l-5.3 2.79 1.01-5.9L3.42 9.63l5.93-.86z"/>' +
        '</svg>';

    function kartCiz(o) {
        return '<article class="szk-kart" data-ar="' + kacir(o.ar) + '"' +
                 ' data-tr="' + kacir(o.tr) + '" data-tur="' + kacir(o.tur || '') + '">' +
                 '<button type="button" class="szk-yildiz" data-fav="1"' +
                   ' aria-pressed="false" aria-label="Favorilere ekle" title="Favorilere ekle">' +
                   YILDIZ + '</button>' +
                 '<div class="szk-ar" dir="rtl">' + kacir(o.ar) + '</div>' +
                 '<div class="szk-tr">' + kacir(o.tr) + '</div>' +
                 (o.tur ? '<div class="szk-tur">' + kacir(o.tur) + '</div>' : '') +
               '</article>';
    }

    function sonucCiz(kap, liste, sorgu) {
        if (!kap) return;
        if (!sorgu) {
            /* Boşken hiçbir şey yazmıyoruz. Yönerge cümlesi de örnek kelime de
               kalktı (Geylani: "bu cümleye ve örnek kelime olan kitap kelimesine
               gerek yok"); klavye zaten ne yapılacağını söylüyor. */
            kap.innerHTML = '';
            return;
        }
        if (!liste.length) {
            kap.innerHTML = '<p class="szk-bos">«' + kacir(sorgu) + '» için sonuç bulunamadı.</p>';
            return;
        }
        var h = '';
        for (var i = 0; i < liste.length; i++) h += kartCiz(liste[i]);
        kap.innerHTML = h;
        if (window.KidefFavori) window.KidefFavori.yildizTazele(kap);
    }

    window.KidefSozluk = {
        duzen: DUZEN, renk: RENK,
        dizin: dizin, ara: ara, sade: sade,
        klavyeCiz: klavyeCiz, sonucCiz: sonucCiz, kartCiz: kartCiz
    };
})();
