/* =========================================================================
   KİDEF — VEZİN GEZİNTİSİ + ANLAM KATMANI            (kaliplartablosu.html)
   -------------------------------------------------------------------------
   İki iş yapar, ikisi de tabloya dışarıdan bağlanır; ana betiğin (
   sarf/kaliplartablosu.js) hiçbir satırı değişmez.

   1) İLERİ TUŞU (sunum kumandası: PageDown / sağ ok / boşluk)
      Bir kök tanımlandıktan sonra her basış, o kökün TANIMLI vezinlerine
      sırayla geçer: kutu ekranın ortasına gelir, kelime türetilir
      (büyütme açıksa büyütülmüş hâliyle). Sıra SON vezinde biter:
      tuş işlevini yitirir ve "vezin kalmadı" uyarısı çalar. Büyütme açık
      olsa bile son vezinde ilerleme yoktur.
      İmleç elle tıklamayla da eşitlenir: öğretmen aradaki bir kutuya
      tıklarsa ileri tuşu oradan devam eder.

   2) ANLAM KATMANI
      Bir vezne tıklanınca o veznin Türkçesi kutunun altında (yer yoksa
      üstünde) küçük bir katman olarak belirir; kutu büyütülmüşse dev
      klonun altına, ona göre büyük yazıyla yerleşir. Üst çubuktaki
      "ANLAM" anahtarı bu katmanı açıp kapatır.

   Anlam kaynağı sözlüğün kendisidir (sozlukVerileri) — Hızlı Liste hangi
   metni gösteriyorsa aynısı okunur; yeni veri girilmez.
   ========================================================================= */
(function () {
    'use strict';

    /* Kumandaların donanımsal olarak gönderdiği tuşlar */
    var ILERI_TUSLARI = ['ArrowRight', 'PageDown', ' ', 'Spacebar'];

    /* Sözlük kaydında "+ eki" sayılmayan (yapısal) anahtarlar */
    var YAPISAL = ['base', 'cekimi', 'isNotVerb', 'ornek', 'tekil', 'cogul',
                   'isDictOnly', 'tip', 'cogulTr', 'suggestsPlus',
                   'hasZamirCekimi', 'zamirBase', 'autoGenerated',
                   'isHiddenInList'];

    /* Tam ekranı kaplayan katmanlar: bunlardan biri açıkken anlam
       katmanı görünmez (üstlerine binmesin). */
    var PERDELER = ['keyboard-overlay', 'marathon-overlay', 'marathon-countdown-overlay',
                    'fast-dictionary-overlay', 'verb-overlay', 'conjugation-overlay',
                    'bab-info-overlay', 'aksam-info-overlay', 'aksam-sema-overlay',
                    'telaffuz-overlay', 'sarfOyunlarOverlay', 'ek-bilgi-perde',
                    'kt-kilavuz', 'rootOfDayOverlay'];

    var sira = -1;          /* gezintideki vezin sırası (-1 = daha başlanmadı) */
    var zincir = null;      /* açık tıklama zincirinin zamanlayıcısı */
    var mesgul = false;     /* geçiş sürüyor: yeni basışlar yutulur */
    var bekci = null;       /* kilit takılırsa açan emniyet zamanlayıcısı */

    /* ---------------------------------------------------------------- */
    /* KÜÇÜK YARDIMCILAR                                                */
    /* ---------------------------------------------------------------- */

    function mobilMi() { return window.innerWidth <= 1024; }

    function buyutmeAcik() {
        if (mobilMi()) return false;
        var c = document.getElementById('zoomToggleCheckbox');
        return !!(c && c.checked);
    }

    function anlamAcik() {
        var c = document.getElementById('anlamToggleCheckbox');
        return !!(c && c.checked);
    }

    function kok() {
        var k = (typeof currentRoot !== 'undefined' && currentRoot) ? String(currentRoot).trim() : '';
        if (k.length !== 3) return '';
        if (typeof sozlukVerileri === 'undefined' || !sozlukVerileri[k]) return '';
        return k;
    }

    function refler() {
        var k = kok();
        if (!k) return [];
        if (typeof getSortedRefsForRoot !== 'function') return [];
        return getSortedRefsForRoot(k) || [];
    }

    function refOku(kutu) {
        if (!kutu) return '';
        var r = kutu.querySelector('.ref');
        var t = r ? String(r.textContent || '').trim() : '';
        if (!t) t = kutu.getAttribute('data-ref') || '';
        return t;
    }

    function kutuBul(ref) {
        var hedef = String(ref).trim();
        var kapsam = mobilMi() ? '#mobile-grid .glass-box' : '.window-pencere .glass-box';
        var liste = Array.prototype.slice.call(document.querySelectorAll(kapsam));
        for (var i = 0; i < liste.length; i++) {
            if (refOku(liste[i]) === hedef) return liste[i];
        }
        return null;
    }

    function dizinBul(rs, ref) {
        var hedef = String(ref).trim();
        for (var i = 0; i < rs.length; i++) {
            if (String(rs[i]).trim() === hedef) return i;
        }
        return -1;
    }

    /* Perdelerin bir kısmı display, bir kısmı opacity/pointer-events ile
       gizleniyor (ör. #sarfOyunlarOverlay hep "block" durur, yalnız
       .open sınıfıyla görünür). O yüzden görünürlük hesaplanan stilden
       okunuyor. Sonuç 150 ms önbelleklenir: tuş basışı ve konumlama
       aynı anda sormasın. */
    function gorunurMu(el) {
        if (!el) return false;
        var h = window.getComputedStyle(el);
        if (!h) return false;
        if (h.display === 'none' || h.visibility === 'hidden') return false;
        if (parseFloat(h.opacity || '1') < 0.05) return false;
        return el.getClientRects().length > 0;
    }

    var perdeSon = 0, perdeDurum = false;
    function perdeAcikMi() {
        var simdi = Date.now();
        if (simdi - perdeSon < 150) return perdeDurum;
        perdeSon = simdi;
        perdeDurum = true;
        /* Bâb odağı / kalıp odağı üst çubuğu kilitler */
        if (document.body && document.body.classList.contains('ust-kilit')) return true;
        if (window.isAtlasMode) return true;
        for (var i = 0; i < PERDELER.length; i++) {
            if (gorunurMu(document.getElementById(PERDELER[i]))) return true;
        }
        perdeDurum = false;
        return false;
    }

    /* Klavyeden yazı yazılıyor mu / gezinti kapalı mı */
    function gezintiKapali() {
        if (perdeAcikMi()) return true;
        if (window.BabOdak && typeof window.BabOdak.aktif === 'function' && window.BabOdak.aktif()) return true;
        if (window.KalipOdak && typeof window.KalipOdak.aktif === 'function' && window.KalipOdak.aktif()) return true;
        var a = document.activeElement;
        if (a && (a.tagName === 'INPUT' || a.tagName === 'TEXTAREA' || a.isContentEditable)) return true;
        return false;
    }

    /* ---------------------------------------------------------------- */
    /* SES SENKRONU                                                      */
    /* ---------------------------------------------------------------- */
    /* Tarayıcı, kullanıcı sayfaya dokunana kadar AudioContext'i ASKIYA
       alıyor. Askıdayken kurulan sesler kaybolmuyor: bağlamın saati
       durduğu için hepsi "sıfır anına" zamanlanıyor ve kullanıcı ilk
       kez dokunduğunda ARKA ARKAYA patlıyor — tık sesleri geç ve toplu
       geliyor. Sayfa açılırken çalan sesler (kendiliğinden yüklenen
       kök, günün kökü vb.) bu yüzden yığılıyordu.
       Çözüm: ilk dokunuştan ÖNCE ses hiç kurulmuyor. Sonrası aynen
       çalışıyor, tek ses gecikmesiz çıkıyor. */
    var etkilesildi = false;
    ['pointerdown', 'keydown', 'touchstart'].forEach(function (t) {
        document.addEventListener(t, function () { etkilesildi = true; }, true);
    });

    function sesKilidi() {
        if (typeof SoundEngine === 'undefined' || SoundEngine._vg) return;
        ['playClick', 'playClose', 'playReset'].forEach(function (ad) {
            var eski = SoundEngine[ad];
            if (typeof eski !== 'function') return;
            SoundEngine[ad] = function () {
                if (!etkilesildi) return;             /* daha dokunulmadı: sessiz */
                return eski.apply(this, arguments);
            };
        });
        SoundEngine._vg = 1;
    }

    /* ---------------------------------------------------------------- */
    /* SES: "BAŞKA VEZİN KALMADI"                                        */
    /* ---------------------------------------------------------------- */
    /* SoundEngine'in kendi sesleri (tık / kapanış / onay) hep TEK vuruş.
       Bu uyarı bilerek ÇİFT ve inen perdeden: kulak onu ötekilerle
       karıştırmasın, "bitti" duyulsun. */
    function vezinBittiSesi() {
        try {
            if (typeof SoundEngine === 'undefined' || !SoundEngine.init) return;
            SoundEngine.init();
            var c = SoundEngine.ctx, t = c.currentTime;
            [[0, 300, 190], [0.14, 210, 120]].forEach(function (v) {
                var o = c.createOscillator(), g = c.createGain();
                o.type = 'sine';
                o.frequency.setValueAtTime(v[1], t + v[0]);
                o.frequency.exponentialRampToValueAtTime(v[2], t + v[0] + 0.10);
                g.gain.setValueAtTime(0, t + v[0]);
                g.gain.linearRampToValueAtTime(0.05, t + v[0] + 0.012);
                g.gain.exponentialRampToValueAtTime(0.001, t + v[0] + 0.12);
                o.connect(g); g.connect(c.destination);
                o.start(t + v[0]); o.stop(t + v[0] + 0.15);
            });
        } catch (e) { /* ses yoksa sessiz geç */ }
    }

    /* Ses kapalı olabilir: son vezin ayrıca iki kez kırmızı çerçeve
       yakıp söndürür. Çerçeve OUTLINE ile veriliyor: büyütülmüş klonun
       kendi gölgesi ve animasyonu !important, onları ezmeye çalışmıyoruz. */
    function sonVezinUyar() {
        var rs = refler();
        if (!rs.length) return;
        var hedef = document.getElementById('crisp-zoom-clone') || kutuBul(rs[rs.length - 1]);
        if (!hedef) return;
        function yak(a) {
            if (a) {
                hedef.style.setProperty('outline', '4px solid rgba(220,53,69,.62)', 'important');
                hedef.style.setProperty('outline-offset', '3px', 'important');
            } else {
                hedef.style.removeProperty('outline');
                hedef.style.removeProperty('outline-offset');
            }
        }
        yak(1);
        setTimeout(function () { yak(0); }, 150);
        setTimeout(function () { yak(1); }, 290);
        setTimeout(function () { yak(0); }, 470);
    }

    /* ---------------------------------------------------------------- */
    /* İLERİ ADIM                                                        */
    /* ---------------------------------------------------------------- */

    /* İLERİ TUŞU = KUTUYA DOKUNMAK. Her basış TEK adım atar, yani tek
       tık sesi çıkar. Kutunun döngüsü:
         büyütme kapalı : 1 kutu seçilir → 2 kök vezne girer (yeşil+anlam)
         büyütme açık   : 1 seçilir → 2 büyür → 3 kök vezne girer → 4 kapanır
       Döngü bitince BİR SONRAKİ basış yeni vezne geçer. */
    function dongusuBitti(kutu) {
        if (!kutu) return true;
        var asama = parseInt(kutu.getAttribute('data-tiklama-sayisi') || '0', 10);
        return asama >= sonAsama();
    }

    function sonAsama() {
        return buyutmeAcik() ? 4 : (mobilMi() ? 1 : 2);
    }

    function ileri() {
        var rs = refler();
        if (!rs.length) return;                       /* kök tanımlı değil: tuş sessiz */

        /* Bir geçiş sürüyorken gelen basış YUTULUR (sıra atlamasın).
           Sekme değişimi bandı 1 sn kaydırıyor; o sırada ikinci basış
           bir vezni görünmeden geçirirdi. */
        if (mesgul) return;

        /* Önce içinde bulunulan veznin adımları biter */
        if (sira >= 0 && sira < rs.length) {
            var simdiki = kutuBul(rs[sira]);
            if (simdiki && !dongusuBitti(simdiki)) {
                if (typeof handleBoxClick === 'function') handleBoxClick(simdiki);
                return;
            }
        }

        /* SON VEZİN: büyütme açık olsun olmasın ilerleme yok */
        if (sira >= rs.length - 1) {
            vezinBittiSesi();
            sonVezinUyar();
            return;
        }
        sira++;
        vezneGit(rs[sira]);
    }

    function vezneGit(ref) {
        var kutu = kutuBul(ref);
        if (!kutu) return;
        mesgul = true;

        if (typeof closeAllZoomedBoxes === 'function') closeAllZoomedBoxes();
        anlamGizle();

        /* Kutu öteki sekmedeyse önce sekmeyi çevir (bant kayması 1 sn sürer) */
        var sekmeDegisti = false;
        if (!mobilMi() && typeof setTab === 'function' && typeof currentTabActive !== 'undefined') {
            if (kutu.closest('#tab1') && currentTabActive !== 0) { setTab(0); sekmeDegisti = true; }
            else if (kutu.closest('#tab2') && currentTabActive !== 1) { setTab(1); sekmeDegisti = true; }
        }

        setTimeout(function () {
            ortala(kutu);
            ilkDokunus(kutu);
        }, sekmeDegisti ? 950 : 0);

        /* Emniyet: bir yerde takılırsa tuş sonsuza dek kilitli kalmasın */
        clearTimeout(bekci);
        bekci = setTimeout(function () { mesgul = false; }, 2600);
    }

    function ortala(kutu) {
        var r = kutu.getBoundingClientRect();
        var orta = window.scrollY + r.top - (window.innerHeight / 2) + (r.height / 2);
        window.scrollTo({ top: Math.max(0, orta), behavior: 'smooth' });
    }

    /* Yeni vezne varılınca YALNIZ TEK dokunuş: kutu seçilir, kelime
       henüz türemez. Eskiden burada arka arkaya iki tık yapılıyordu
       (seç + türet); ikisi 45 ms arayla iki tık SESİ çıkarıyordu ve
       "çift ses" olarak duyuluyordu. Artık her basış tek adım, tek ses. */
    function ilkDokunus(kutu) {
        if (zincir) { clearTimeout(zincir); zincir = null; }
        if (typeof handleBoxClick !== 'function') { mesgul = false; return; }

        /* Daha önce türetilmemiş kutuyu sıfırdan başlat: aşama sayacı
           eski bir ziyaretten kalmış olabilir. */
        if (!kutu.classList.contains('kok-turendi')) kutu.removeAttribute('data-tiklama-sayisi');

        handleBoxClick(kutu);
        mesgul = false;
    }

    /* ---------------------------------------------------------------- */
    /* ANLAM KATMANI                                                     */
    /* ---------------------------------------------------------------- */

    var katman = null, katmanKutu = null, katmanZaman = null, cerceve = null;

    function ekBul(o) {
        if (!o) return null;
        for (var k in o) {
            if (YAPISAL.indexOf(k) !== -1) continue;
            if (o[k] && typeof o[k] === 'object') return o[k].base ? o[k].base : o[k];
        }
        return null;
    }

    /* Sözlükteki örnek cümle(ler): kimi kayıtta tek nesne, kimisinde
       dizi ({ar, tr} ve seyrek olarak {not}). Hepsi diziye çevrilir. */
    function ornekListesi(d) {
        var ham = null;
        if (!d) return [];
        if (d.ornek) ham = d.ornek;
        else if (d.base && d.base.ornek) ham = d.base.ornek;
        else if (d.tekil && d.tekil.base && d.tekil.base.ornek) ham = d.tekil.base.ornek;
        if (!ham) return [];
        var dizi = Array.isArray(ham) ? ham : [ham];
        return dizi.filter(function (o) { return o && (o.ar || o.tr); });
    }

    /* Hızlı Liste hangi metni gösteriyorsa aynı sıra ile okunur */
    function anlamBul(k, ref) {
        var sonuc = { emoji: '', tr: '', ornekler: [] };
        if (typeof sozlukVerileri === 'undefined') return sonuc;
        var kv = sozlukVerileri[k];
        if (!kv) return sonuc;
        var d = kv[ref];
        if (!d) d = kv[String(ref)];
        if (!d) d = kv[parseInt(ref, 10)];
        if (!d) return sonuc;

        if (d.tekil && d.tekil.base) {
            sonuc.emoji = d.tekil.base.emoji || '';
            sonuc.tr = d.tekil.base.trText || '';
        } else if (d.base) {
            sonuc.emoji = d.base.emoji || '';
            sonuc.tr = d.base.trText || d.base.tr || '';
        } else {
            sonuc.emoji = d.emoji || '';
            sonuc.tr = d.trText || d.tr || '';
        }

        /* Temel anlam boşsa ilk "+" ekinin anlamı gösterilir */
        if (!sonuc.tr || !String(sonuc.tr).trim()) {
            var ek = ekBul(d) || (d.tekil ? ekBul(d.tekil) : null);
            if (ek) {
                sonuc.tr = ek.trText || ek.tr || '';
                sonuc.emoji = ek.emoji || sonuc.emoji;
            }
        }
        sonuc.ornekler = ornekListesi(d);
        return sonuc;
    }

    function katmanKur() {
        if (katman) return katman;
        var s = document.createElement('style');
        s.textContent =
            '#vezin-anlam-katmani{position:fixed;z-index:1000000;pointer-events:none;' +
            'display:none;max-width:min(560px,86vw);box-sizing:border-box;' +
            'padding:9px 18px;border-radius:14px;background:#ffffff;' +
            'border:2px solid #e2e8f0;box-shadow:0 10px 26px rgba(0,0,0,.16);' +
            "font-family:'Arakom',sans-serif;font-weight:normal;color:#1f2937;" +
            'font-size:20px;line-height:1.35;text-align:center;direction:ltr;' +
            'opacity:0;transform:translateY(-4px);transition:opacity .18s ease,transform .18s ease}' +
            '#vezin-anlam-katmani.vg-acik{display:block;opacity:1;transform:none}' +
            /* Büyütme perdesinde: kelime solda, anlam onun SAĞINDA ve iri */
            /* Yan panel SABİT bir kutu: eni ve boyu kelimeye göre
               değişmez. Üstte anlam, altta örnek cümleler; örnekler
               sığmazsa kendi içinde dikey kayar. */
            '#vezin-anlam-katmani.vg-yan{padding:22px 30px;border-radius:24px;' +
            'line-height:1.25;border-width:3px;box-shadow:0 22px 55px rgba(0,0,0,.22);' +
            'display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start;' +
            'overflow:hidden;pointer-events:auto}' +
            '#vezin-anlam-katmani.vg-yan.vg-orneksiz{justify-content:center}' +
            '#vezin-anlam-katmani.vg-yan.vg-orneksiz .vg-ornekler{display:none}' +
            '#vezin-anlam-katmani.vg-yan .vg-bas{flex:0 0 auto;text-align:center;' +
            'direction:ltr;unicode-bidi:isolate}' +
            '#vezin-anlam-katmani:not(.vg-yan) .vg-ornekler{display:none}' +
            '#vezin-anlam-katmani.vg-yan .vg-ornekler{flex:1 1 auto;min-height:0;' +
            'overflow-y:auto;overflow-x:hidden;margin-top:16px;padding-top:14px;' +
            'border-top:2px solid #edf1f6;-webkit-overflow-scrolling:touch;' +
            'overscroll-behavior:contain}' +
            '#vezin-anlam-katmani.vg-yan .vg-ornekler::-webkit-scrollbar{width:10px}' +
            '#vezin-anlam-katmani.vg-yan .vg-ornekler::-webkit-scrollbar-track' +
            '{background:#f3f6fa;border-radius:6px}' +
            '#vezin-anlam-katmani.vg-yan .vg-ornekler::-webkit-scrollbar-thumb' +
            '{background:#c3ccd8;border-radius:6px}' +
            /* Altta devamı olduğunu belli eden yumuşama */
            '#vezin-anlam-katmani.vg-yan.vg-kayar .vg-ornekler' +
            '{-webkit-mask-image:linear-gradient(to bottom,#000 calc(100% - 38px),transparent);' +
            'mask-image:linear-gradient(to bottom,#000 calc(100% - 38px),transparent)}' +
            '#vezin-anlam-katmani .vg-ornek{padding:9px 2px;border-bottom:1px dashed #e7ecf3}' +
            '#vezin-anlam-katmani .vg-ornek:last-child{border-bottom:0}' +
            '#vezin-anlam-katmani .vg-oar{font-size:40px;line-height:1.55;color:#111;' +
            'direction:rtl;text-align:right}' +
            '#vezin-anlam-katmani .vg-otr{font-size:25px;line-height:1.35;color:#5b6472;' +
            'direction:ltr;text-align:left;margin-top:2px}' +
            '#vezin-anlam-katmani .vg-onot{font-size:21px;color:#8a93a0;direction:ltr;' +
            'text-align:left;margin-top:3px}' +
            '#vezin-anlam-katmani.vg-buyuk{font-size:31px;padding:13px 26px;border-radius:18px}' +
            '#vezin-anlam-katmani .vg-emoji{margin-right:8px}' +
            '#vezin-anlam-katmani.vg-yan .vg-emoji{display:block;margin:0 0 6px 0;font-size:.85em}' +
            '#vezin-anlam-katmani::after{content:"";position:absolute;' +
            'left:var(--vg-okx,calc(50% - 9px));' +
            'width:0;height:0;border-left:9px solid transparent;border-right:9px solid transparent}' +
            '#vezin-anlam-katmani.vg-alt::after{top:-11px;border-bottom:11px solid #e2e8f0}' +
            '#vezin-anlam-katmani.vg-ust::after{bottom:-11px;border-top:11px solid #e2e8f0}' +
            '#vezin-anlam-katmani.vg-yan::after{left:-16px;top:var(--vg-oky,50%);' +
            'transform:translateY(-50%);border-left:0;border-right:16px solid #e2e8f0;' +
            'border-top:14px solid transparent;border-bottom:14px solid transparent}';
        document.head.appendChild(s);

        katman = document.createElement('div');
        katman.id = 'vezin-anlam-katmani';
        katman.setAttribute('role', 'status');
        katman.setAttribute('aria-live', 'polite');
        /* Örnekler kaydırılabilsin diye yan panel tıklama alıyor; ama
           tıklama sayfaya SIZMAMALI — sayfanın "dışarı tıklandı"
           dinleyicisi büyütmeyi kapatıyor. */
        ['click', 'mousedown', 'pointerdown', 'touchstart'].forEach(function (t) {
            katman.addEventListener(t, function (e) { e.stopPropagation(); }, false);
        });
        document.body.appendChild(katman);
        return katman;
    }

    function anlamGoster(kutu) {
        if (!anlamAcik()) { anlamGizle(); return; }
        var k = kok();
        if (!k || !kutu) { anlamGizle(); return; }

        var bilgi = anlamBul(k, refOku(kutu));
        if (!bilgi.tr || !String(bilgi.tr).trim()) { anlamGizle(); return; }

        katmanKur();
        katman.innerHTML =
            '<div class="vg-bas" dir="ltr">' +
            (bilgi.emoji ? '<span class="vg-emoji">' + bilgi.emoji + '</span>' : '') +
            '<span class="vg-metin"></span></div>' +
            '<div class="vg-ornekler"></div>';
        katman.querySelector('.vg-metin').textContent = String(bilgi.tr).trim();
        ornekleriYaz(bilgi.ornekler);
        katman.classList.toggle('vg-orneksiz', !bilgi.ornekler.length);
        katmanKutu = kutu;
        katman.classList.add('vg-acik');
        konumla();
        izlemeyeBasla();
        /* Büyütme klonu tıklamadan ~10 ms sonra doğuyor ve 0,25 sn'lik
           bir açılış animasyonu var: katman ölçüyü ona göre yeniden
           alsın, yerinde zıplama görünmesin. */
        [60, 180, 330].forEach(function (ms) { setTimeout(konumla, ms); });
    }

    /* Örnek cümleler: Arapçası sağa yaslı ve iri, Türkçesi altında.
       Metinler textContent ile yazılıyor — sözlükten gelen içerik
       HTML olarak yorumlanmasın. */
    function ornekleriYaz(liste) {
        var kap = katman.querySelector('.vg-ornekler');
        if (!kap) return;
        kap.innerHTML = '';
        kap.scrollTop = 0;
        (liste || []).forEach(function (o) {
            var satir = document.createElement('div');
            satir.className = 'vg-ornek';
            if (o.ar) {
                var a = document.createElement('div');
                a.className = 'vg-oar';
                a.setAttribute('dir', 'rtl');
                a.textContent = String(o.ar).trim();
                satir.appendChild(a);
            }
            if (o.tr) {
                var t = document.createElement('div');
                t.className = 'vg-otr';
                t.setAttribute('dir', 'ltr');
                t.textContent = String(o.tr).trim();
                satir.appendChild(t);
            }
            if (o.not) {
                var n = document.createElement('div');
                n.className = 'vg-onot';
                n.textContent = String(o.not).trim();
                satir.appendChild(n);
            }
            kap.appendChild(satir);
        });
    }

    function anlamGizle() {
        if (!katman) return;
        katman.classList.remove('vg-acik');
        katmanKutu = null;
        izlemeyiDurdur();
    }

    /* BÜYÜTME PERDESİNDE YERLEŞİM
       Dev kelime ve kahverengi kök taşı SOLDA açılır, anlam onların
       SAĞINDA iri puntoyla durur. Anlam kalan yere sığacak en büyük
       puntoyu seçiyor. */
    var YAN_PUNTO = [64, 56, 48, 42, 36, 31];
    var SOL_PAY = 0.028;          /* dev kutunun sol kenarına bırakılan pay */
    var ARA = 30;                 /* kutu ile anlam paneli arası */
    var SAG_PAY = 24;             /* panelin sağ kenar payı */
    var PANEL_YUK_UST = 620;      /* panelin en fazla boyu */

    /* KUTU DOĞDUĞU ANDA, SABİT ÖLÇÜSÜYLE, SOLDA AÇILIR.
       Kutunun eni eskiden içindeki kelimeye göreydi: vezin (فَعِلَ) ile
       türemiş kelime (عَلِمَ) aynı enle yazılmadığı için kök vezne
       girince kutu büyüyüp küçülüyordu — "esneme". Artık kutunun eni
       de boyu da sabit: en = ekranın %45'i, boy = tam puntonun satır
       yüksekliği + kutu payları.
       Sözlükteki 4617 tek kelimelik yazılışın en genişi 180 punto ile
       587 px; %45'lik kutunun iç genişliğine sığmayan yaklaşık %1'lik
       uzun kelimede KUTU değil YAZI biraz küçülür, kutu yerinde kalır.
       ANLAM kapalıysa hiç dokunmuyoruz: kutu eskisi gibi ortada,
       kendi eniyle açılır. */
    var EN_ORANI = 0.45;
    var TAM_PUNTO = 0;
    var olcer = null;

    function yaz(el, ozellik, deger) {           /* değişmiyorsa yazma */
        if (!el || el.style.getPropertyValue(ozellik) === deger) return;
        el.style.setProperty(ozellik, deger, 'important');
    }

    /* Yazı enini gizli bir ölçekle alıyoruz: klonun kendi ölçüsü açılış
       animasyonunun ölçeğinden etkilendiği için güvenilmez. */
    function metinEni(metin, punto) {
        if (!olcer) {
            olcer = document.createElement('span');
            olcer.style.cssText = 'position:fixed;left:-99999px;top:0;visibility:hidden;' +
                "white-space:nowrap;font-family:'Arakom',sans-serif;font-weight:normal;line-height:1.2";
            document.body.appendChild(olcer);
        }
        olcer.style.fontSize = punto + 'px';
        olcer.textContent = metin;
        return olcer.getBoundingClientRect().width;
    }

    function klonaSigdir(klon, icEn) {
        var yazi = klon.querySelector('.ar, .ar-small');
        if (!yazi) return;
        if (!TAM_PUNTO) TAM_PUNTO = parseFloat(window.getComputedStyle(yazi).fontSize) || 180;
        var gerekli = metinEni(String(yazi.textContent || '').trim(), TAM_PUNTO) * 1.02;
        if (gerekli > icEn) {
            yaz(yazi, 'font-size', Math.max(80, Math.floor(TAM_PUNTO * icEn / gerekli)) + 'px');
        } else if (yazi.style.fontSize) {
            yazi.style.removeProperty('font-size');
        }
    }

    function klonuSolaCek(klon) {
        if (!klon || !anlamAcik()) return 0;
        var vw = window.innerWidth;
        var sabitEn = Math.round(vw * EN_ORANI);
        var h = window.getComputedStyle(klon);
        var yanPay = parseFloat(h.paddingLeft) + parseFloat(h.paddingRight) +
                     parseFloat(h.borderLeftWidth) + parseFloat(h.borderRightWidth);
        var dikPay = parseFloat(h.paddingTop) + parseFloat(h.paddingBottom) +
                     parseFloat(h.borderTopWidth) + parseFloat(h.borderBottomWidth);
        if (!isFinite(yanPay)) yanPay = 118;
        if (!isFinite(dikPay)) dikPay = 78;

        if (!TAM_PUNTO) {
            var y = klon.querySelector('.ar, .ar-small');
            if (y) TAM_PUNTO = parseFloat(window.getComputedStyle(y).fontSize) || 180;
        }
        yaz(klon, 'width', sabitEn + 'px');
        yaz(klon, 'min-width', sabitEn + 'px');
        yaz(klon, 'max-width', sabitEn + 'px');
        /* Boy da sabit: uzun kelimede yazı küçülse bile kutu alçalmasın */
        yaz(klon, 'min-height', Math.round(dikPay + (TAM_PUNTO || 180) * 1.2) + 'px');
        klonaSigdir(klon, sabitEn - yanPay);

        var solKenar = Math.max(36, vw * SOL_PAY);
        var merkez = Math.round(solKenar + sabitEn / 2);
        yaz(klon, 'left', merkez + 'px');
        yaz(document.getElementById('crisp-root-clone'), 'left', merkez + 'px');
        return merkez;
    }

    /* Klon gövdeye eklenir eklenmez yerine otursun: zamanlayıcıyla
       yakalanırsa önce ortada bir kare görünüp sonra sola sıçrıyor. */
    var klonGozcu = null;
    function klonIzle() {
        if (klonGozcu || !document.body || typeof MutationObserver !== 'function') return;
        klonGozcu = new MutationObserver(function (kayitlar) {
            for (var i = 0; i < kayitlar.length; i++) {
                var eklenen = kayitlar[i].addedNodes;
                for (var j = 0; j < eklenen.length; j++) {
                    var n = eklenen[j];
                    if (!n || n.nodeType !== 1) continue;
                    if (n.id === 'crisp-zoom-clone') {
                        klonuSolaCek(n);
                    } else if (n.id === 'crisp-root-clone') {
                        var z = document.getElementById('crisp-zoom-clone');
                        if (z && z.style.left) n.style.setProperty('left', z.style.left, 'important');
                    }
                }
            }
        });
        klonGozcu.observe(document.body, { childList: true });
    }

    /* TİTREME OLMASIN DİYE: yerleşim yalnız GERÇEKTEN değişince
       hesaplanıyor. Eskiden 400 ms'lik yoklama her turda punto denemesi
       yapıp ölçü alıyordu; sınırdaki metinlerde iki punto arasında
       gidip gelebiliyor, kutu da açılış animasyonu sürerken ölçüldüğü
       için katman oynuyordu. Artık ölçüler DÜZEN değerlerinden
       (offsetWidth/Height, hesaplanmış top) alınıyor ve imza aynıysa
       hiçbir stil yazılmıyor. */
    var yanIz = '';

    function yanaYerlestir(klon) {
        var vw = window.innerWidth, vh = window.innerHeight;
        var merkez = klonuSolaCek(klon);
        if (!merkez) return false;

        var en = klon.offsetWidth || 0;
        var merkezY = parseFloat(window.getComputedStyle(klon).top);
        if (!isFinite(merkezY)) merkezY = vh * 0.35;

        var sol = Math.round(merkez + en / 2 + ARA);
        var panelEn = Math.round(vw - sol - SAG_PAY);
        if (panelEn < 240) return false;              /* yer yok: alta düş */

        var kutuYuk = klon.offsetHeight || 290;
        var kutuUst = Math.round(merkezY - kutuYuk / 2);
        /* Panel BOYU da sabit: örnekler sığmazsa panel uzamaz, örnek
           alanı kendi içinde kayar. Üst kenarı dev kutuyla aynı hizada
           başlar, aşağıda ekran payına kadar iner. */
        var orneksiz = katman.classList.contains('vg-orneksiz');
        var panelYuk = orneksiz ? kutuYuk : Math.round(Math.max(kutuYuk,
            Math.min(PANEL_YUK_UST, vh - kutuUst - 24)));

        var iz = [vw, vh, en, sol, panelEn, panelYuk, kutuUst, katman.textContent].join('|');
        if (iz === yanIz && katman.classList.contains('vg-yan')) return true;
        yanIz = iz;

        katman.classList.add('vg-yan');
        katman.classList.remove('vg-alt', 'vg-ust', 'vg-buyuk');
        /* EN ve BOY SABİT: panel her vezinde aynı dikdörtgen. Böylece
           anlam değişince ne panel ne de dev kutu yer/ölçü değiştirir. */
        katman.style.width = panelEn + 'px';
        katman.style.maxWidth = panelEn + 'px';
        katman.style.height = panelYuk + 'px';
        katman.style.minHeight = panelYuk + 'px';

        /* Anlam yazısı: panelin üst yarısını aşmayan en büyük punto
           (yalnız imza değişince denenir). Örnek yoksa daha cömert. */
        var bas = katman.querySelector('.vg-bas');
        var sinir = orneksiz ? panelYuk - 44 : panelYuk * 0.46;
        for (var i = 0; i < YAN_PUNTO.length; i++) {
            katman.style.fontSize = YAN_PUNTO[i] + 'px';
            if (!bas || bas.offsetHeight <= sinir) break;
        }

        var ust = Math.round(Math.max(12, Math.min(kutuUst, vh - panelYuk - 12)));
        katman.style.left = sol + 'px';
        katman.style.top = ust + 'px';

        /* Örnekler sığmıyorsa alt kenar yumuşasın: devamı olduğu
           anlaşılsın, kesilmiş gibi durmasın. */
        var orn = katman.querySelector('.vg-ornekler');
        katman.classList.toggle('vg-kayar', !!orn && orn.scrollHeight > orn.clientHeight + 2);
        /* Ok, dev kelimenin ortasını göstersin */
        var okY = Math.max(24, Math.min(merkezY - ust, panelYuk - 24));
        katman.style.setProperty('--vg-oky', Math.round(okY) + 'px');
        return true;
    }

    /* Katman, ekranda GÖRÜNEN öğeye yapışır: kutu büyütülmüşse dev
       klona, değilse kutunun kendisine. */
    function konumla() {
        if (!katman || !katman.classList.contains('vg-acik')) return;
        if (!katmanKutu || !katmanKutu.isConnected || perdeAcikMi()) { anlamGizle(); return; }

        var klon = document.getElementById('crisp-zoom-clone');
        if (klon && yanaYerlestir(klon)) return;

        katman.classList.remove('vg-yan');
        katman.style.fontSize = '';
        katman.style.width = '';
        katman.style.maxWidth = '';
        katman.style.height = '';
        katman.style.minHeight = '';
        yanIz = '';
        var hedef = klon || katmanKutu;
        katman.classList.toggle('vg-buyuk', !!klon);

        var r = hedef.getBoundingClientRect();
        if (!r.width && !r.height) { anlamGizle(); return; }

        var o = katman.getBoundingClientRect();
        var bosluk = klon ? 22 : 14;
        var altta = r.bottom + bosluk + o.height <= window.innerHeight - 8;
        var ust = altta ? (r.bottom + bosluk) : (r.top - bosluk - o.height);

        katman.classList.toggle('vg-alt', altta);
        katman.classList.toggle('vg-ust', !altta);

        var sol = r.left + r.width / 2 - o.width / 2;
        sol = Math.max(8, Math.min(sol, window.innerWidth - o.width - 8));
        katman.style.top = Math.max(8, ust) + 'px';
        katman.style.left = sol + 'px';

        /* Ok, kutunun ortasını göstersin (katman kenara dayandıysa kayar) */
        var okX = r.left + r.width / 2 - sol;
        okX = Math.max(18, Math.min(okX, o.width - 18));
        katman.style.setProperty('--vg-okx', (okX - 9) + 'px');
    }

    function izlemeyeBasla() {
        if (cerceve !== null) return;
        window.addEventListener('scroll', tazele, true);
        window.addEventListener('resize', tazele);
        cerceve = 1;
        katmanZaman = setInterval(function () {
            if (!katman || !katman.classList.contains('vg-acik')) return;
            konumla();
        }, 400);
    }

    function izlemeyiDurdur() {
        if (cerceve === null) return;
        window.removeEventListener('scroll', tazele, true);
        window.removeEventListener('resize', tazele);
        cerceve = null;
        if (katmanZaman) { clearInterval(katmanZaman); katmanZaman = null; }
    }

    var bekleyen = false;
    function tazele() {
        if (bekleyen) return;
        bekleyen = true;
        requestAnimationFrame(function () { bekleyen = false; konumla(); });
    }

    /* ---------------------------------------------------------------- */
    /* TABLOYA BAĞLANMA                                                  */
    /* ---------------------------------------------------------------- */

    function tiklamaSonrasi(kutu) {
        if (!kutu) return;

        /* İmleci elle tıklanan kutuya eşitle: ileri tuşu oradan devam eder */
        var i = dizinBul(refler(), refOku(kutu));
        if (i !== -1) sira = i;

        /* Dev kutu açıksa: kelime değişmiş olabilir, sığdırmayı tazele.
           (Kutunun ölçüsü sabit; yalnız gerekiyorsa yazı küçülür.) */
        var acikKlon = document.getElementById('crisp-zoom-clone');
        if (acikKlon) klonuSolaCek(acikKlon);

        /* ANLAM, KÖK VEZNE GİRİNCE ÇIKAR.
           İlk tıklama kutuyu yalnız SEÇİYOR (kırmızı vurgu, kutuda hâlâ
           vezin duruyor: فَعَلَ). Anlam o anda görünürse kelime
           türemeden Türkçesi okunmuş olur. Bu yüzden katman ancak
           kelime türetildiğinde (kutu 'kok-turendi' olunca) açılır. */
        if (!kutu.getAttribute('data-tiklama-sayisi')) { anlamGizle(); return; }
        if (kutu.classList.contains('kok-turendi')) anlamGoster(kutu);
        else anlamGizle();
    }

    function sifirla() {
        sira = -1;
        mesgul = false;
        if (zincir) { clearTimeout(zincir); zincir = null; }
        if (bekci) { clearTimeout(bekci); bekci = null; }
        anlamGizle();
    }
    window.KidefVezinGezinti = { ileri: ileri, sifirla: sifirla, anlamGizle: anlamGizle };

    function baglan() {
        klonIzle();
        sesKilidi();
        /* 1) Kutu tıklaması */
        if (typeof window.handleBoxClick === 'function' && !window.handleBoxClick._vg) {
            var eskiTik = window.handleBoxClick;
            window.handleBoxClick = function (kutu) {
                var s = eskiTik.apply(this, arguments);
                try { tiklamaSonrasi(kutu); } catch (e) { /* yoksay */ }
                return s;
            };
            window.handleBoxClick._vg = 1;
        }

        /* 2) Kök değişimi → gezinti başa döner */
        ['selectReadyVerb', 'confirmRoot', 'resetTableOnly'].forEach(function (ad) {
            if (typeof window[ad] !== 'function' || window[ad]._vg) return;
            var eski = window[ad];
            window[ad] = function () {
                var s = eski.apply(this, arguments);
                try { sifirla(); } catch (e) { /* yoksay */ }
                return s;
            };
            window[ad]._vg = 1;
        });

        /* 3) Büyütme kapanınca katman kutuya geri yapışsın */
        if (typeof window.closeAllZoomedBoxes === 'function' && !window.closeAllZoomedBoxes._vg) {
            var eskiKapat = window.closeAllZoomedBoxes;
            window.closeAllZoomedBoxes = function () {
                var s = eskiKapat.apply(this, arguments);
                try { tazele(); } catch (e) { /* yoksay */ }
                return s;
            };
            window.closeAllZoomedBoxes._vg = 1;
        }

        /* 4) ANLAM anahtarı */
        var anahtar = document.getElementById('anlamToggleCheckbox');
        if (anahtar && !anahtar._vg) {
            anahtar.addEventListener('change', function () {
                if (typeof SoundEngine !== 'undefined' && SoundEngine.playClick) SoundEngine.playClick();
                if (!anahtar.checked) { anlamGizle(); return; }
                /* Açılınca ekranda kökü girmiş (türetilmiş) aktif kutu
                   varsa anlamı hemen göster; yalnız seçili kutu için
                   bekle — anlam kelime türeyince çıkar. */
                var aktif = document.querySelector('.window-pencere .glass-box.current-active-red.kok-turendi') ||
                            document.querySelector('#mobile-grid .glass-box.current-active-red.kok-turendi');
                if (aktif) anlamGoster(aktif);
            });
            anahtar._vg = 1;
        }
    }

    /* 5) İLERİ TUŞU — yakalama evresinde; sayfanın kaydırması araya girmesin */
    document.addEventListener('keydown', function (e) {
        if (ILERI_TUSLARI.indexOf(e.key) === -1) return;
        if (e.ctrlKey || e.metaKey || e.altKey) return;
        if (gezintiKapali()) return;
        if (!refler().length) return;                 /* kök yoksa sayfa normal davransın */
        e.preventDefault();
        e.stopPropagation();
        ileri();
    }, true);

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', baglan);
    } else {
        baglan();
    }
    /* Ana betiğin geç tanımladığı fonksiyonlar için ikinci tur */
    window.addEventListener('load', baglan);
})();
